### ISSUE TITLE
Undergarden BOP biome gening in the overworld

### ISSUE THREAD

**Issue by scalda** [Team-RTG/Realistic-Terrain-Generation#240] opened 2015-10-23 13:35 UTC
Hi all i have just found a undergarden nether biome spawn in the overworld

Regards

Scalda

**Comment by whichonespink44** [comment] 2015-10-23 13:39
So bizarre!! Do you have any other mods installed?

**Comment by scalda** [comment] 2015-10-23 13:41
Not biome generating ones. but there are 85 mods in total loaded

**Comment by whichonespink44** [comment] 2015-10-23 13:50
Ok, if you could pastebin your `fml-client-latest.log` here, I'll see if I can figure out what's going on.

I've created a new branch to work on these BOP issues, including #225 so hopefully I'll be able to find the cause of all these BOP issues.

**Comment by scalda** [comment] 2015-10-23 13:58
here is the log

https://dl.dropboxusercontent.com/u/8871364/fml-server-latest.log

**Comment by whichonespink44** [comment] 2015-10-23 14:48
From the Undergarden page on the [BOP wiki](http://biomesoplenty.wikia.com/wiki/Undergarden):

_"Strangely, in BoP-1.7.10-2.1.0.1283-universal, this biome generates in the overworld, bug?"_

I know you're using 2.1.0.1396, but it seems to be a known issue with BOP.

Maybe try using a different version of BOP to see if it still happens. I've used version 2.1.0.1387 quite a lot and haven't seen that biome in the overworld.

I'll close the issue for now, but let me know how you get on.

**Closed by whichonespink44** 2015-10-23 14:48 UTC
