### ISSUE TITLE
Flat Bayou Terrain

### ISSUE THREAD

**Issue by Quizer9O8** [Team-RTG/Realistic-Terrain-Generation#1002] opened 2016-10-17 16:02 UTC
Affected Mod Versions:
RTG1.10.2-4.1.1.2, GeographiCraft-1.9.4-.0.7.4, Biomes O' Plenty-1.10.2-5.0.0.2068
- Forge version:Forge-12.18.2.2105
- RTG version: RTG1.10.2-4.1.1.2

Issue Description:
The terrain for the Bayou seems to be for the most part really flat, shouldnt there be puddles, shallow lakes and more swampy like terrain be there just like the vanilla-counterpart?
![2016-10-14_21 27 23](https://cloud.githubusercontent.com/assets/19509275/19445201/9c2f8954-9493-11e6-8fbe-f8991097b419.png)
![2016-10-14_21 27 30](https://cloud.githubusercontent.com/assets/19509275/19445203/9c309d44-9493-11e6-83fc-596f628250ad.png)
##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by whichonespink44** [comment] 2016-10-28 15:37
@Quizer9O8 We've been unable to reproduce these non-lake, non-puddle versions of the BOP Bayou... is this still happening for you?

**Comment by whichonespink44** [comment] 2016-11-02 17:31
We've managed to reproduce this and we have a plan to fix it (RTG ponds FTW!!!)... should be in this Sunday's release.

**Comment by whichonespink44** [comment] 2016-11-05 03:14
Fixed in 782c797

**Closed as completed by whichonespink44** 2016-11-05 03:14 UTC
Labels: bug, bug: unconfirmed, 1.10
