### ISSUE TITLE
Adding Abyssalcraft compatibility 

### ISSUE THREAD

**Issue by CliveBarker** [Team-RTG/Realistic-Terrain-Generation#492] opened 2016-02-08 15:42 UTC
Abyssalcraft is a constantly updated mod with almost 300,000 downloads at curse.
http://www.curse.com/mc-mods/minecraft/abyssalcraft

Currently RTG crash when generating a new world when Abyssalcraft is  installed.
Crash: http://pastebin.com/xu3BzD0R

These are the Abyssalcraft biomes that need a Realistic version:

Coralium Infested Swamp
Darklands
Darklands Forest
Darklands Highland
Darklands Mountain
Darklands Plains

Here is the Abyssalcraft config file (note that this mod adds many biomes more than the ones I listed, but only those listed generate at the over-world dimension. 

http://pastebin.com/SCwzJbQn

Thanks in advance.

**Comment by whichonespink44** [comment] 2016-02-08 19:31
Duplicate of #281 - I'm thinking of adding inherent support for AbyssalCraft in the next major release, rather than waiting for the API to be finished. You can follow #281 for progress updates.

**Closed by whichonespink44** 2016-02-08 19:31 UTC
Labels: duplicate
