### ISSUE TITLE
Half-cobble/half-sandstone villages

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#705] opened 2016-05-15 20:05 UTC
Minecraft 1.7.10
RTG 0.8.0 RC-2
Seed: 3029737
Loaded on BiomeTweaker with BOP RTG tweaks
Coordinates on top right
Only happens sometimes, hard to reproduce
![2016-05-14_13 25 21](https://cloud.githubusercontent.com/assets/11594018/15276461/b243a240-1a9d-11e6-92c9-bc142206f423.png)

**Comment by VelocityRa** [comment] 2016-05-17 17:24
The world looks completely different to me, with the same versions, seed and location.
1) Is the seed correct?
2) Did you tweak *any* of the configs? (BiomeTweaker's RTG preset mainly).
3) Which BiomeTweaker's version do you use? I tested with the latest Release, `BiomeTweaker-1.7.10-1.2.128`

**Comment by whichonespink44** [comment] 2016-05-17 18:01
@chaNcharge Can you supply a fml-client-latest.log file so we can investigate further?

**Comment by chaNcharge** [comment] 2016-05-18 05:49
The seed definitely is correct, I did change the RTG mod config, village sizes have been increased to 1 and village spacing are the default values. I did have BOP installed on 1.7.10. Every time I regenerated this world, it was always a desert, no matter what. Make sure you're teleporting to the right coordinates. I'll see if I can get a log file, I'll post it as soon as I have it.

**Comment by VelocityRa** [comment] 2016-05-18 11:30
Yeah, I did get the seed and the villages to work (they didn't generate with your settings, I had to lower the min/max values), but I can't reproduce, villages work fine for me near biome borders, where the issue is.
![2016-05-18_14 21 46](https://cloud.githubusercontent.com/assets/6632271/15356970/a5931e36-1d04-11e6-83c6-203e50a6223b.png)

It may indeed happen but is hard to reproduce, like you said. Without that I can't do much though I'm afraid. The issue has been resolved for the vast majority of the cases, (I flew around quite a bit and didn't see anything) I'm not sure that spending more time on this would be beneficial. I'll still leave this open in case some other dev manages to reproduce it.

Thank you for reporting it though @chaNcharge, I've seen you quite a lot around here, your help is appreciated!

**Comment by chaNcharge** [comment] 2016-05-19 02:37
I'm using the dev version, but yes it is hard to reproduce. I'm on a phone right now so I can't send a log yet, but I'll try to get one soon.

**Comment by chaNcharge** [comment] 2016-05-19 05:57
So I regenerated the world for what seems like 15 times, and I managed to sort of reproduce the bug. It's not quite the bug I was describing, but definitely a step in the right direction. 
![2016-05-18_22 46 46](https://cloud.githubusercontent.com/assets/11594018/15383860/257ef5c0-1d4b-11e6-9735-093f14f3cbf9.png)
Does it seem sort of off to the overall theme of the village? It is not a separate village, it's inside just one village. Here's the fml-client-latest.log file: https://drive.google.com/file/d/0B3ZoX-8LP704U2l0a2lsZkFJa28/view?usp=sharing

**Comment by topisani** [comment] 2016-05-19 17:21
I dont htink theres a lot to do about this - we are fairly limited by those forge events

**Comment by Zeno410** [comment] 2016-05-19 20:21
If we're using MapGenVillageRTG, can we set it on a village placement check?

**Comment by topisani** [comment] 2016-05-20 10:00
yes, but we'd need to overrwrite StructureVillagePieces, which might be a bad idea

**Comment by whichonespink44** [comment] 2016-05-20 10:35
I was always quite reluctant to do our own StructureVillagePieces, but it might be worth a shot if it's going to totally resolve this issue.

My only concern is that it's going to cause compatibility issues with other village-related mods somehow, though I don't know if it would.

In any case, if we did try to write our own StructureVillagePieces, what would we need to do in terms of a 'placement check'? Do you mean checking the biome from within StructureVillagePieces before deciding which block to place, or something different?

**Comment by topisani** [comment] 2016-05-20 16:06
just checking it when the village is started, and then passing it down to the rest of the things

**Comment by whichonespink44** [comment] 2016-05-20 16:26
Isn't that what we're already doing with the Forge event? We're checking the biome during preDecoration and then passing it to the Forge event, but... that doesn't seem to work 100% of the time.

How will passing it to StructureVillagePieces be any different?

**Comment by topisani** [comment] 2016-05-20 16:32
because the biome forge is passing is weird... i think its on a per house scale

**Comment by whichonespink44** [comment] 2016-05-20 16:38
It's worth a shot I guess.

Let's look at it after 0.8 is released :+1:

**Comment by whichonespink44** [comment] 2016-06-08 19:51
I think this is rare enough that we can leave it until after 1.0 is released.

**Comment by chaNcharge** [comment] 2016-06-20 05:40
Seems to be more common in RTG 1.0 snapshot 2, got the bug to reproduce after 1 world regeneration compared to originally 10-15. Same seed, same location, although I increased village size to 1 (from 0) and village spread to vanilla values.
![2016-06-19_22 33 38](https://cloud.githubusercontent.com/assets/11594018/16184173/e1af9d58-366e-11e6-9c25-a8b3b0e850b3.png)

**Comment by chaNcharge** [comment] 2016-06-23 18:26
Just tested this in the official 1.0 release, still present

**Comment by srs-bsns** [comment] 2016-06-24 12:19
@chaNcharge, can you pastebin/gist the list of mods you are using?
Also, what is the frequency that you observe this happening?

I did some testing a couple of days ago with a small group of mods that alter villages and out of ~100 villages observed I only found 1 that had a single broken building, similar to as you reported here: #686, but I didn't observe anything like in the screenshots in this issue.

**Comment by Zeno410** [comment] 2016-06-24 16:56
@srs-bsns is that broken building reproducible? Mine (also rare) have not been.

**Comment by chaNcharge** [comment] 2016-06-25 04:20
It doesn't happen too often, but this also occurs by itself and biomes o plenty with the RTG BOP tweaks

**Comment by srs-bsns** [comment] 2016-06-25 08:45
@Zeno410, I didn't attempt to reproduce it, and sadly I no longer have the config setup to go back and try.
However, for future reference on 'cut off buildings' (probably not related to this issue): https://github.com/MinecraftForge/MinecraftForge/issues/3020

**Comment by srs-bsns** [comment] 2016-07-03 19:14
If this is the same Issue as the race condition in Forge (#3020) then the fix for it (https://github.com/MinecraftForge/MinecraftForge/pull/3061) may fix this issue, but unfortunately the fix will only be in the latest Forge. Maybe there's a way for us to incorporate the fix in RTG to prevent this?

**Comment by Zeno410** [comment] 2016-07-03 21:23
My take is no, we can't do it. We'd have to hack around in critical MC/Forge operations (the Anvil loader itself, ick)

**Comment by srs-bsns** [comment] 2016-07-04 03:07
Oh well, If we can't, it's not a big deal. I am mostly concerned with moving forward, so hopefully this issue is caused by the same double chunk gen race condition that is causing #686. We atleast shouldn't see this sort of thing in RTG 2._._ and beyond.

**Comment by whichonespink44** [comment] 2016-07-12 21:51
Should be fixed in 625b591 - closing until it rears its ugly head again.

**Closed by whichonespink44** 2016-07-12 21:51 UTC
Labels: 1.7.10, bug, confirmed

**Comment by srs-bsns** [comment] 2016-07-12 23:30
@chaNcharge
I have not observed this happening once, in hundreds of test worlds created, so I still feel that this is either a mod interaction bug, or possibly https://github.com/MinecraftForge/MinecraftForge/issues/3020, or a combination of both. In any case there isn't anything we can really do about it.

In the case that this really was RTG's fault, then I know exactly where the problem was. It was in code added to fix #392, which has just been removed because it no longer seems to be relevant. But let us know if you still observe this happening.
