### ISSUE TITLE
[RTG 0.5.0 snapshot-1] crash on world creation with Witchery.

### ISSUE THREAD

**Issue by MrGraphic** [Team-RTG/Realistic-Terrain-Generation#380] opened 2016-01-06 00:01 UTC
I tried both layouts, with and without CC - same results. 0.4 works without issue. I remeber that in the past Emoniph added some compatibility on his side in case of ATG.

java.lang.RuntimeException
	at rtg.world.biome.WorldChunkManagerRTG.<init>(WorldChunkManagerRTG.java:50)
	at rtg.world.WorldTypeRTG.getChunkManager(WorldTypeRTG.java:27)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:61)
	at com.emoniph.witchery.dimension.WorldProviderDreamWorld.func_76572_b(WorldProviderDreamWorld.java:75)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
	at net.minecraft.world.World.<init>(World.java:244)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Ezoteric** [comment] 2016-01-06 00:33
That's weird I use witchery in my default test environment and never had a witchery crash. Can you dump the whole fml latest log plz

**Comment by MrGraphic** [comment] 2016-01-06 01:02
Sure http://pastebin.com/X0ExkCRR .

**Comment by Haggle1996** [comment] 2016-01-06 01:04
Looks like this may be a duplicate of #382

**Comment by Zeno410** [comment] 2016-01-06 03:14
That was a deliberate crash I put in because I was expecting problems with non-Overworld dimensions. Witchery is trying to create the Dream dimension with the RTG chunk manager - will that work?

**Comment by whichonespink44** [comment] 2016-01-06 08:06
Fixed in aea3b24

**Closed by whichonespink44** 2016-01-06 08:06 UTC
Labels: crash, unconfirmed
