### ISSUE TITLE
spawning water temples in weird places

### ISSUE THREAD

**Issue by taluseve** [Team-RTG/Realistic-Terrain-Generation#917] opened 2016-08-22 17:54 UTC
##### Affected Mod Versions: 1.10.2

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version:2056
- RTG version:1.10.2
##### Issue Description:

(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
##### Steps to reproduce the issue: (If it's easily reproducible.)

1.load rtg 
2.go to gamemode 3 you will see them in every biome when they should be in ocean
3.
##### Extra Information:its not crashing but you can find them in forest not deep under the ground and alot of time u see them under rivers.  they are placed in perfectly square areas underground with alot of protectors around them, alot more than should be.
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by taluseve** [comment] 2016-08-22 17:55
was excited for this back  but  cant play when those temples are everywhere, nowhere is safe and most temples are found around rivers and forest biomes.

**Comment by whichonespink44** [comment] 2016-08-22 18:04
Dupe of #913 - we're working on this now and will hopefully be releasing the next snapshot tonight.

**Comment by taluseve** [comment] 2016-08-22 18:05
ty very much for all your hardwork, great mod

**Closed as completed by whichonespink44** 2016-08-22 18:04 UTC
Labels: duplicate

**Comment by whichonespink44** [comment] 2016-08-22 21:11
Fixed in a2b70b6 & new snapshot has been released: https://minecraft.curseforge.com/projects/realistic-terrain-generation/files/2325679
