### ISSUE TITLE
[RTG 1.0 Snapshot-2] Village farms sometimes follow terrain

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#765] opened 2016-06-20 05:45 UTC
This doesn't happen with every village farm but basically, the farm kinda appears to follow the terrain its on and ends up sinking abruptly. Hard to explain, but screenshot says it all.
Village spread set to vanilla values
Village size: 1
Seed: 3029737
![2016-06-19_22 34 40](https://cloud.githubusercontent.com/assets/11594018/16184227/77df668c-366f-11e6-8ee6-3d02bc8ca106.png)
![2016-06-19_22 44 55](https://cloud.githubusercontent.com/assets/11594018/16184239/8f257872-366f-11e6-8898-47a94e4bcbb0.png)

**Comment by topisani** [comment] 2016-06-20 14:22
that actually looks pretty awesome :P other than that, no idea

**Comment by whichonespink44** [comment] 2016-06-22 06:18
I'm not able to reproduce the 'terrain following' issue using just the latest version of RTG with that seed + vanilla village settings and village size = 1.

@chaNcharge Can you confirm this is still happening in v1.0?

What I did notice (again), however, is that villages seem to be ignoring decorations sometimes:

![2016-06-22_07 11 57](https://cloud.githubusercontent.com/assets/10927161/16256302/2f6e7420-3849-11e6-8f0a-781cef62d775.png)

I've actually seen this in my pre 1.0 testing as well, but I'm assuming the only way around it is to write our own village system? Something we might need to look at, depending on how many people are affected by this.

**Comment by whichonespink44** [comment] 2016-11-06 22:44
No one's reported anything like this for months, so closing for now.

**Closed by whichonespink44** 2016-11-06 22:44 UTC
Labels: bug, mc-1.7.10, unconfirmed
