### ISSUE TITLE
Console spam with RTG, Ender IO and Forestry

### ISSUE THREAD

**Issue by Jomik** [Team-RTG/Realistic-Terrain-Generation#1022] opened 2016-10-30 18:21 UTC
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: forge-1.10.2-12.18.2.2105
- RTG version: RTG-1.10.2-4.1.1.4
- Forestry version: forestry_1.10.2-5.2.14.270
- Ender Core version: EnderCore-1.10.2-0.4.1.55-beta
- Ender IO version: EnderIO-1.10.2-3.0.1.120_beta
##### Issue Description:

(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
This issue is currently happening on a server I run for a closed group. I noticed that we got RTG-Warn in the server console and investigated. It started when we first set up a tree farm using the Ender IO Farming Station, and has been going on since then.
Unsure if this is related https://github.com/SleepyTrousers/EnderIO/issues/3744 as there seems to be an error in the interaction between Ender IO and Forestry. However I don't understand why RTG would react at this point.
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Start a world with Ender IO, Forestry and RTG using "Realistic" world generation.
2. Setup an Ender IO Farming Station with Apple Oak Saplings.
3. Watch your console get spammed, possibly coinciding with tree growth.
##### Extra Information:

[Server thread/WARN] [FML]: [RTG-WARN] Could not get sapling meta from non-sapling BlockState (tile.for.saplingGE.name).

**Comment by whichonespink44** [comment] 2016-10-30 20:15
This seems to be caused by Forestry's saplings not extending the vanilla BlockSapling:

https://github.com/ForestryMC/ForestryMC/blob/c289590740e47c1df5d08cab6dea0d78eb7599f7/src/main/java/forestry/arboriculture/blocks/BlockSapling.java#L51

However, the console spam shouldn't be happening - it's just leftover debug code that should be silenced unless RTG has debugging enabled.

We'll fix this for the next release, which will probably be next Sunday.

**Comment by whichonespink44** [comment] 2016-10-30 20:24
Fixed in 53347f8.

**Closed as completed by whichonespink44** 2016-10-30 20:24 UTC
Labels: bug, confirmed, 1.10

**Comment by darkphan** [comment] 2016-11-02 07:44
These entries still exist in build 4.1.1.5

**Comment by srs-bsns** [comment] 2016-11-02 10:15
The only way you could possibly be getting those warning messages now is if you have `B:"Enable Debugging"` set to `true` in RTG's config file.

**Comment by darkphan** [comment] 2016-11-02 16:15
Enable Debugging is set to false and we definitely see the messages still (this was 14 minutes ago from this post):

[16:00:04] [Server thread/WARN] [FML/]: [RTG-WARN] Could not get sapling meta from non-sapling BlockState (tile.for.saplingGE.name).

**Comment by srs-bsns** [comment] 2016-11-02 17:09
Please see 53347f8. This was fixed and the fix is in RTG 4.1.1.5, so the only way you should see this log message is if:
1. `B:"Enable Debugging"` is set to `true` (in rtg.cfg on the server), or
2. You are using an older version of RTG than 4.1.1.5

**Comment by whichonespink44** [comment] 2016-11-02 17:11
Sorry guys, this hasn't been released yet. It's fixed in dev, but we're not releasing again until Sunday, but it will definitely be fixed then.
