### ISSUE TITLE
Crash with Volcanoes and HarvestCraft/Farseek

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#926] opened 2016-08-25 23:15 UTC
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: forge-1.10.2-12.18.1.2071
- RTG version: RTG-1.10.2-4.1.1.2-snapshot-2
- Farseek: Farseek-1.9.4-1.1
- Streams: Streams-1.9.4-0.2.1
##### Issue Description:

Have seen a few Volcanoes generated around the world just fine, but this one crashed the game to desktop.
##### Steps to reproduce the issue: (If it's easily reproducible.)

[crash-2016-08-26_07.11.02-server.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/438221/crash-2016-08-26_07.11.02-server.txt)

**Comment by whichonespink44** [comment] 2016-08-28 17:14
Here's another crash report that's similar to this:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3328

**Comment by whichonespink44** [comment] 2016-08-29 12:03
The good news is that I've added some code in 136f0af that will stop this from crashing... however, the nature of the crash suggests that there's something else at play here, and it might not even have anything to do with volcanoes, Streams **or** HarvestCraft (although I'm a bit suspicious that both crash reports involve volcanoes).

@Zygus42 To help us get to the bottom of this, could you download the new snapshot when it's released later today, set "Patch Biome ID"=**-1** (negative one) in [rtg.cfg](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/etc/config/RTG/rtg.cfg#L32), and try creating a new world with the same seed to see if it crashes again. It **should** crash, and when it does, the new crash report will contain new information that will help us figure out what's going on.

**Comment by Zygus42** [comment] 2016-08-29 21:20
Sorry - can't reproduce the crash.  In those 4 days I put together the final version of my pack to start a new world, so mods got updated, added, taken out and configs got changed.  When I try it now with the same seed, no volcano and no crash - on either snapshot.  Using the crash report I could rebuild the mods folder, but the configs got changed quite a bit and I have no way to roll those back.

**Comment by whichonespink44** [comment] 2016-08-29 22:41
@Zygus42 No worries - we'll try to reproduce it using the suspected mods and see if we can dig a little deeper.

**Comment by whichonespink44** [comment] 2016-09-12 23:37
Closing this since it can't be reproduced. Will re-open if it appears again.

**Closed as completed by whichonespink44** 2016-09-12 23:37 UTC
Labels: bug: unconfirmed, 1.10
