### ISSUE TITLE
BOP sub-biomes generate, even if disabled in RTG configs

### ISSUE THREAD

**Issue by scalda** [Team-RTG/Realistic-Terrain-Generation#225] opened 2015-10-17 09:04 UTC
Hi all, i am running rtg latest version of the mod in a dev pack for iskall85 and villages aren't spawning in the BOP biomes. is there anychance this can and/or will be implemented?

regards

Scalda

**Comment by Ezoteric** [comment] 2015-10-17 15:54
Hmmz I haven't tested the latest version but I always had villages there :o

**Comment by scalda** [comment] 2015-10-17 16:07
Strange we can't seem to get any to spawn in a bop biome but found one in a
magical forest from thaumcraft

**Comment by whichonespink44** [comment] 2015-10-17 16:14
Villages should be capable of generating in BOP biomes. I'll do a quick test to see if I can spot one.

**Comment by whichonespink44** [comment] 2015-10-17 16:34
![image](https://cloud.githubusercontent.com/assets/10927161/10559996/0c818384-74f5-11e5-8068-0265ce4d576b.png)

Seems to be working alright. I haven't checked every biome, but they should be able to generate in any biome they would normally be able to with just BOP enabled.

Let me know how you get on.

**Comment by scalda** [comment] 2015-10-17 20:10
Ok, we will keep looking i'm wondering if they aren't spawning as much as our terrain is quite hilly from rtg

**Comment by whichonespink44** [comment] 2015-10-17 22:40
RTG's current bias towards hilly/mountainous terrain is probably the biggest factor at play here. I was going to wait until Beta before addressing that issue, but I might see if I can do something before then. I'll close this for now, but feel free to re-open if you still don't find any.

**Comment by scalda** [comment] 2015-10-18 07:05
what is your village weighting in you BOP config?

**Comment by Ezoteric** [comment] 2015-10-18 08:44
Standard at my setup cause the villages are often too big as it is :p

**Comment by whichonespink44** [comment] 2015-10-18 09:13
"Distance between villages" = 32

But here's the interesting part...

Bayou=**false**

The screenshot I posted above was in a Bayou... so it looks like RTG ignores the BOP biome flags for village generation.

**Comment by Ezoteric** [comment] 2015-10-18 09:18
hmmz thats weird yes.

**Comment by whichonespink44** [comment] 2015-10-18 09:20
I wonder if the other village settings have any effect... I know the ones in EB do... when I had EB installed, I changes the distance to 8 and the size to 6, and massive villages were absolutely everywhere.

**Comment by scalda** [comment] 2015-10-18 14:19
actually i'm in the same boat with the biomes spawning when they are disabled, as i have mangrove disabled yet still spawns in world.

**Comment by whichonespink44** [comment] 2015-10-18 16:24
Yeah, just to clarify... RTG's configs intentionally override other mods' configs for biome generation. For example, if you set `Bayou=true` in BOP's _"overworld biomes to generate"_ section, but you set `generateBOPbayou=true` in RTG's config, the Bayou biome will generate. So RTG controls biome generation, regardless of what you set in BOP's (or any other mod's) configs.

However... I was under the impression that RTG respected other mods' village config settings. It respects the village settings in EB, as mentioned above - but it doesn't seem to be respecting BOP's village config settings. And I'm not sure why. I'll have to look into this one further.

**Comment by scalda** [comment] 2015-10-18 17:19
yeah i see but i had it round the other way to what you have said, and was still getting the mangrove biome i have now disabled in both with the weights turned of and still had it generate.

**Comment by whichonespink44** [comment] 2015-10-19 16:09
I think I may have fixed this issue. Here's a snapshot of 0.0.13 if anyone wants to test it out: https://goo.gl/nLQlLi

**Comment by scalda** [comment] 2015-10-19 16:45
ok thanks will check it out and let you know

**Comment by scalda** [comment] 2015-10-21 09:58
thats great villages seem to be spawning now i have found a couple. the next thing is i'm still getting mangrove biome spawn even thou it is disabled in both rtg and BOP

**Comment by Ezoteric** [comment] 2015-10-21 10:07
Download source and remove it ;)

**Comment by whichonespink44** [comment] 2015-10-21 11:59
@scalda I'll take another look at this tonight. Something odd is definitely going on.

**Comment by scalda** [comment] 2015-10-21 12:18
ok thank you, i thought it might be ids but i can't find anything conflicting in my config files

**Comment by whichonespink44** [comment] 2015-10-21 18:25
Speaking of config files, would you be able to zip up your RTG config folder and attach it to this issue? It's probably fine, but I'd just like to rule it out for definite.

**Comment by scalda** [comment] 2015-10-21 19:44
Here's a link to my rtg files

https://dl.dropboxusercontent.com/u/8871364/RTG.zip

**Comment by scalda** [comment] 2015-10-22 18:59
Did you manage to look at my config files?

**Comment by whichonespink44** [comment] 2015-10-22 21:49
Not yet, sorry. I just need to finish a handful more biomes for the 0.0.13 release and then I'll be on with bug squashing.

**Comment by whichonespink44** [comment] 2015-10-23 19:52
Ok, I've figured out what's causing this... basically, the only biomes that are generating when disabled are BOP's '[sub-biomes](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/api/content/BOPCBiomes.java#L67)' - and the reason they're generating even when disabled is because their 'parent' biome is enabled.

For example, the Quagmire is a [sub-biome of the Sludgepit biome](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/core/BOPBiomes.java#L323), so... the only way to disable the Quagmire would be to also disable the Sludgepit. And if you disable the Sludgepit, the Quagmire biome won't generate even if it's enabled.

So...

I'm not quite sure what the best approach is here... I could either:

a) Remove all BOP sub-biomes from RTG (this would also get rid of [ocean sub-biomes](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/core/BOPBiomes.java#L309) as well)

or...

b) Add comments to the config files explaining how sub-biomes work. So the options in the ConfigBOP.cfg file would look something like this:

'[Sludgepit, Quagmire, Silkglades]
enableSludgepitBiomes=true'


I think I'm probably going to go with option B, unless someone can think of a better solution.

Let me know what you guys think.

**Comment by scalda** [comment] 2015-10-23 20:58
ok so that will explain why i was getting mangrove as it's a ocean sub biome, can't you have your config similar to how BOP have there's as you can disable each biome individually?

**Comment by whichonespink44** [comment] 2015-10-23 22:12
Ignore everything that I said in my previous post.. it doesn't work like that at all (sounded good though! :stuck_out_tongue: )

The reason they're being generated even though they're disabled is because of a simple typo in the RTG code. I'm fixing it now and it will be part of the 0.0.13 release.

(Sorry for putting you through all this trouble)

**Comment by whichonespink44** [comment] 2015-10-23 22:17
@scalda - can you just confirm that it was only the Mangrove biome that was generating even though it was disabled? Because that's the only biome that had the typo, and that was the only biome that I was able to reproduce the bug for.

**Comment by scalda** [comment] 2015-10-24 04:54
It was the only one that I noticed to be spawning that was disabled

**Comment by whichonespink44** [comment] 2015-10-24 06:33
:+1:

**Closed by whichonespink44** 2015-10-24 06:33 UTC
Labels: pending
