### ISSUE TITLE
Mesa Platue F and Ice Plains causing bad generation

### ISSUE THREAD

**Issue by Kehaan** [Team-RTG/Realistic-Terrain-Generation#358] opened 2015-12-22 20:38 UTC
Using RTG 0.4, it looks like there is some generation issues with Mesa Platue F and Ice Plains. Causing some bleeding. This is with ExtraBiomes XL.

Screenshots:
https://gyazo.com/555fd92065d51110f670ad600bb4fb44
https://gyazo.com/2874346a2d08cd539cdaed9f65d2b719
https://gyazo.com/e8faa31b6ce682f8d743caca2446cecc
https://gyazo.com/07d7a1be5fe26c7df6366a13efcef48f

Dynmap:
https://gyazo.com/8d736ea908c152ee3eca807bcc136895

**Comment by Ezoteric** [comment] 2015-12-22 22:19
besides the grass this is normal biome bleeding :)

**Comment by whichonespink44** [comment] 2015-12-22 23:34
Yes, unfortunately when the bleed creeps into elevated terrain, it looks awful.

There's another issue (#312) related to this... hopefully it will get resolved in the next update.

**Comment by CyborgDino** [comment] 2015-12-24 16:28
On a side note, shouldn't that Mesa Plateau F have forest in it?

**Comment by whichonespink44** [comment] 2016-01-20 17:32
Duplicate of #312

**Closed by whichonespink44** 2016-01-20 17:32 UTC
