### ISSUE TITLE
Crash when Generating New Chunks in a World

### ISSUE THREAD

**Issue by Whimsyturtle** [Team-RTG/Realistic-Terrain-Generation#1049] opened 2016-11-14 03:17 UTC
##### Affected Mod Versions:
Mekanism, MrTJPCore

- Forge version: 10.13.4.1614
- RTG version: 1.1.1.2

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
Crash when Generating New Chunks in a World.
(Note: This May Not be Realistic Terrain Generation's Fault, but it was Referenced in the Crash Report. This May be Caused by MrTJPCore / Mekanism)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Generate New Chunks in an Existing World in a Multiplayer Server
2.
3.

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

Crash Log:
http://pastebin.com/4JsJKAY1

Issue in MrTJPCore's Issues: https://github.com/MrTJP/MrTJPCore/issues/20
Issue in Mekanism's Issues: https://github.com/aidancbrady/Mekanism/issues/3975

**Comment by whichonespink44** [comment] 2016-11-14 08:29
Since you're using 1.1.1.2, this is not likely an RTG issue, as we recently put in 'graceful failing' for structure generation. This means that instead of crashing during structure generation, RTG will just stop generating the structure at the point of failure, allowing the world to carry on generating.

If this turns out to not be the case, please let us know so we can investigate further.

**Comment by srs-bsns** [comment] 2016-11-14 08:37
This is caused (AGAIN) by Minecraft's non-threadsafe Hashmap iteration while the Mekanism salt generator is trying to generate salt at the same time that RTG is trying to place a structure, likely a village part, in the same chunk.

@whichonespink44 I can't remember, did you backport our crash prevention from 1.10.2 for this sort of thing? It would likely work good in cases like this, and the worst case scenario would be an unfinished structure placement, but a rare ugly/unfinished village structure is better than a crash, IMO.

![membercmes](https://cloud.githubusercontent.com/assets/8453133/20258032/86d5d700-aa1b-11e6-835f-fc9cf631bd01.png)

Edit: Ninja'd again

**Comment by whichonespink44** [comment] 2016-11-14 08:39
Forgot to mention... if you want a faster resolution to this issue, try reproducing the crash with as few mods as possible and posting that crash report as well. The crash report in the OP has a lot of mods, so unless one of the other authors knows immediately why it's crashing, they're not going to be able to reproduce it themselves with that many mods. And if we can't reproduce it, we can't fix it.

Let us know how it goes.

**Comment by whichonespink44** [comment] 2016-11-14 08:40
Double ninja'd!! xD

**Comment by Cronosus** [comment] 2016-12-05 20:27
not relevant to OP, but i have today crash too on generating world, and i found problem on generating of some biomes.. not generated structures and trees, jut dirt biomes (example: http://cronos.wz.cz/mc/2016-12-05_21.28.24.png)..
i use BoP and biometweaker, and other mods..

crash here: http://cronos.wz.cz/mc/crash-2016-12-05_21.22.48-server.txt

**Comment by srs-bsns** [comment] 2016-12-05 21:45
@Cronosus Update to: https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v1.7.10-1.1.1.3

**Comment by srs-bsns** [comment] 2017-01-30 19:34
Closing this as there isn't much more we can do to prevent CMEs like this in 1.7.10 as it is a crash with how Minecraft works. CMEs like this don't appear to happen in new versions of Minecraft.

**Closed as completed by srs-bsns** 2017-01-30 19:34 UTC
Labels: bug: unconfirmed, 1.7
