### ISSUE TITLE
Sand on village farmland

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#1060] opened 2016-11-26 18:35 UTC
##### Affected Mod Versions:

- Forge version:1.10.2- 12.18.2.2151
- RTG version: 4.1.1.8

##### Issue Description:

Sand spawns on village farmland areas, possibly meant for sugar canes to be there, but the sugar canes are not present

##### Extra Information:
- Seed for the world I found them in: -42786915464327544822
- Loaded with BiomeTweaker using BOP tweaks and BOP 5.0.0.2093
![2016-11-26_09 54 06](https://cloud.githubusercontent.com/assets/11594018/20642456/02818226-b3c4-11e6-9a45-c2e459df23a9.png)

**Comment by Quizer9O8** [comment] 2016-11-27 12:46
Besides sand gravel sometimes tend to spawn in there.

**Comment by Ezoteric** [comment] 2016-12-18 09:03
yeah i had this as well with the newest version :(

**Comment by srs-bsns** [comment] 2016-12-18 11:42
After looking at vanilla village generation code (for MC 1.10.2), this should not be happening, and RTG only calls the vanilla generator and does not alter villages in any way.

This is most likely caused by another mod that either:
1. alters village gen. (Any mod that adds custom crops to village farms)
2. does any kind of world gen that adds sand splotches after villages have been generated.

I'm going to close this for now until someone can offer proof of a RTG fault.

Here are proof images that this happens without RTG (Taken from the MMD Andromeda server that uses BoP worldtype and has custom village crops):
![2016-12-18_06 33 42](https://cloud.githubusercontent.com/assets/8453133/21293238/39d48a8c-c4ec-11e6-9f9a-1a1f1799a22a.png)
![2016-12-18_06 34 04](https://cloud.githubusercontent.com/assets/8453133/21293240/3d3fd866-c4ec-11e6-86b9-7c221c82dfd8.png)

**Closed as completed by srs-bsns** 2016-12-18 11:42 UTC
Labels: bug, bug: other, 1.10

**Comment by Ezoteric** [comment] 2016-12-18 12:53
yeah i was thinking bop or forestry so i guess its bop :)

**Comment by srs-bsns** [comment] 2016-12-18 13:34
Yes, my guess is BoP. In my screenshots above, this has occured in the BoP Meadow, and the BoP Meadow biome adds a generator for sand that I'm pretty sure runs after the village generator, in which case this is the likely result sometimes.

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenMeadow.java#L56

I'll investigate this further, and if it is indeed happening with BoP, then maybe I'll create a patch for BoP to add a clause to prevent the sand from replacing farmland, which should remedy this issue, and PR it.

Or maybe @Adubbz can look into it if he has time.

**Comment by srs-bsns** [comment] 2016-12-18 17:58
Here's another example from Grassland where you can see that there used to be farmland and the plant blocks were turned into their item counterparts after the blocks were changed to gravel:

![2016-12-18_12 26 49](https://cloud.githubusercontent.com/assets/8453133/21295371/b33176e4-c521-11e6-8173-972c2c9d217f.png)
