### ISSUE TITLE
Gaps on world generation

### ISSUE THREAD

**Issue by Scratchman** [Team-RTG/Realistic-Terrain-Generation#1174] opened 2017-05-21 05:04 UTC
- Forge version: forge-1.10.2-12.18.3.2297
- RTG version: RTG-1.10.2-4.2.0.0-snapshot-1

##### Issue Description:
Using your latest snapshot I've created a new world, but I'm seeing lots of "streaking"

http://map.imaginescape.tk/

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Use chunkgen-1.10.2-1.5.0 to pregenerate the world
2. render with dynmap

I can provide a list of mods in the modpack if it would help diagnose the problem

##### Extra Information:
I didn't see any errors in the server log that might explain the issue.

**Comment by srs-bsns** [comment] 2017-05-21 07:29
Not sure what's going on here yet, but clearly something is. You can see in the last screenshot that it doesn't appear to be restricted to chunk borders, as there doesn't appear to be signs of anything getting cut off at the borders, but the streak is most definately vertical in nature.

Seed: 3459487736926468020

![2017-05-21_03 18 20](https://cloud.githubusercontent.com/assets/8453133/26281968/a9887bc0-3dd4-11e7-89c3-25b3b97c206c.png)
![2017-05-21_03 19 01](https://cloud.githubusercontent.com/assets/8453133/26281971/ae04e5bc-3dd4-11e7-8ca5-863b1408e3ab.png)
![2017-05-21_03 21 06](https://cloud.githubusercontent.com/assets/8453133/26281972/b115c7c6-3dd4-11e7-9ed3-2a0d86b2af72.png)

**Comment by whichonespink44** [comment] 2017-05-21 07:36
That's the issue I saw earlier before we released the snapshot.

When I restarted MC, created a new world with the same seed, and flew to the same location, the undecorated streak was gone, so we put it down to a one-off de-sync issue.

Maybe it's related to pregenning?

**Comment by Scratchman** [comment] 2017-05-21 07:43
as you can see from the dynmap, half the map isn't generated yet, so i'll fly over that way and see if i can find any gaps.

**Comment by whichonespink44** [comment] 2017-05-21 07:45
![2017-05-21_08 43 35](https://cloud.githubusercontent.com/assets/10927161/26282082/a963401c-3e01-11e7-8696-81a59092b5d9.png)

Seed: 3459487736926468020

I didn't pre-gen anything - I just flew to the location in the screenshots above, and... no streaks.

¯\\\_(ツ)_/¯

**Comment by Scratchman** [comment] 2017-05-21 08:56
I think it must have something to do with pregenning then. I went to an area of the map that hasn;t been generated yet, wandered around for a while.

https://www.dropbox.com/s/1jpxb5fow8veimd/2017-05-21_01.44.59.png

But, I have pregenerated the map using the same pregen mod, a few times,  with earlier versions of RTG and I never saw this happen. The server is currently in a test phase but the players are expecting the main world to be pregenerated when the server launches.

**Comment by srs-bsns** [comment] 2017-05-21 09:02
It can't be a pre-generation issue because I never used pre-generation for the world in my screenshots, and the streak in that world was right near the spawn area.

What's troubling, is that recreating that same world mutliple times, I am not able to reproduce this issue in any way, and I haven't yet seen this in any other worlds I've created so far either.

**Comment by Scratchman** [comment] 2017-05-21 09:19
The seed I'm using is 1958433064931045313

You can see from dynmap that it's happened on most of the left side of the map, and that area was pregenerated, but the area i just traveled, that has some of the same biomes, is just fine.

So I'm not sure what's going on.

**Comment by srs-bsns** [comment] 2017-05-21 11:36
There is most definately some kind of issue here, but it may take some time to get sorted.

**Comment by srs-bsns** [comment] 2017-05-21 11:47
Some more images of evidence...

A screenshot of Scratchman's DynMap:
![dynmap1](https://cloud.githubusercontent.com/assets/8453133/26283587/47e9188c-3df9-11e7-95b8-92ab2ea190e9.png)

A world radially pre-generated with ChunkGen, saved and reloaded. The bare spot is the border between the pre-genned chunks (before save) and manually generated chunks (after save):
![2017-05-21_07 22 52](https://cloud.githubusercontent.com/assets/8453133/26283554/137a8e50-3df9-11e7-9fdb-f07d08164b72.png)

An animated gif of 2 separate worlds with the same seed (that should be identical) that shows a great difference in the generated trees (This may be a separate issue, but may contribute to this one.) The bare spots are where saved chunks meet new ones.:
![uhoh](https://cloud.githubusercontent.com/assets/8453133/26283607/b99602f6-3df9-11e7-9bf0-3e86bb25b093.gif)

**Comment by Sunconure11** [comment] 2017-05-21 17:15
I think I have an idea as to what could hypothetically cause this specific issue, although it is not the same as the chunkgen issue I had.

This thread HYPOTHETICALLY has such info, if this is the case: http://www.minecraftforum.net/forums/minecraft-discussion/seeds/2557524-a-very-strange-seed

**Comment by srs-bsns** [comment] 2017-05-21 18:29
@Sunconure11 Negative. This is an issue with our generator that has been introduced recently. This issue doesn't exist in 4.1.1.4, only in the latest snapshot.

**Comment by Scratchman** [comment] 2017-05-21 20:56
I am going to wipe the main map and pregen it again, just to see what happens.

I'll join you in discord later when the map has a significant area pregenerated and i can turn on dynmap again.

Pregenerating the map and having dynmap on at the same time would probably melt the server. 😆

**Comment by Scratchman** [comment] 2017-05-22 22:12
So it seems the streaking is only affecting the left side of the map and seems to stop around x=1600.
I totally wiped the map and let the server pregen the map, using the same seed, for the last 24 hours and came up with this.

http://imgur.com/a/96MQA

I'm going to shut dynmap down again and pregen the map some more, try and fill out the rest of it to the borders.

**Comment by Scratchman** [comment] 2017-05-22 22:47
So it seems the streaking is only affecting the left side of the map and seems to stop around x=1600.
I totally wiped the map and let the server pregen the map, using the same seed, for the last 24 hours and came up with this.

http://imgur.com/a/96MQA

I'm going to shut dynmap down again and pregen the map some more, try and fill out the rest of it to the borders.

**Comment by Scratchman** [comment] 2017-05-23 09:46
And the streaking returned on the right side of the map. I'm generating a dynmap now and I'll leave it enabled for now, but still generate some more of the map.

**Comment by whichonespink44** [comment] 2017-05-23 15:14
We think we've isolated the cause of the issue... just need to find some time to fix it.

**Comment by whichonespink44** [comment] 2017-07-03 11:15
Fixed in dad0733

**Comment by srs-bsns** [comment] 2018-08-16 10:09
This still happens and needs to be solved before 1.12 is released.

**Comment by srs-bsns** [comment] 2019-07-17 22:47
Due to change made to decoration, this needs to be reconfirmed.

**Comment by srs-bsns** [comment] 2019-10-15 04:35
Closing as this no longer appears to happen and was probably resolved by removing the delayed decoration system and using proper coords for decorations.

**Closed as completed by srs-bsns** 2019-10-15 04:35 UTC
Labels: bug: unconfirmed, 1.12
