### ISSUE TITLE
Config options for mix blocks

### ISSUE THREAD

**Issue by KeepOnDigging** [Team-RTG/Realistic-Terrain-Generation#499] opened 2016-02-11 10:52 UTC
I would love to see config options to set mix block id/meta/size on a per-biome basis.

**Comment by whichonespink44** [comment] 2016-02-12 10:17
Biome config options for surface blocks are [in the works](https://github.com/Team-RTG/Realistic-Terrain-Generation/compare/dev...biome-configs) now and will be partially implemented in 0.6.1

However, there are a lot of biomes, and... unfortunately, because of the way the surface system is setup, it will take a good while to get all biomes' surface blocks customisable. We'll probably start with all vanilla biomes, and then work our way through the mods.

**Comment by whichonespink44** [comment] 2016-02-22 10:10
Closing as duplicate of #322. This has been implemented for vanilla biomes and will roll out into mod biomes over the next couoke of releases.

**Closed by whichonespink44** 2016-02-22 10:10 UTC
Labels: accepted, feature-request, in-progress
