### ISSUE TITLE
WorldGen Problem With HeatAndClimate

### ISSUE THREAD

**Issue by touhouzun** [Team-RTG/Realistic-Terrain-Generation#1222] opened 2017-09-18 13:05 UTC
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:1.10.2-forge1.10.2-12.18.3.2477
- RTG version:RTG-1.10.2-4.2.0.0-snapshot-5
- HeatAndClimateLib version:1.10.2_1.5.14
- HeatAndClimateMod version:1.10.2_1.5.17
- HeatAndClimateASM version:1.1.5

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
Screenshots always fail to upload due to my playing region.
My rtg config is "enable caves=false" and "enable ravines=false",other density configs aren't touched.
Without h&c,caves are fewer(but can't be fully disabled;ravines can be disabled);With h&c and it's default config,the underground is a mess like vanilla,and cave&ravine generation behaves like rtg doesn't exist.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.Install newest rtg and h&c
2.Create a new world with rtg world type
3./gamemode 3 and dive down

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/
Heat&Climate is created by a Japanese user called defeatedcrow.He(?)does use github.

**Comment by srs-bsns** [comment] 2017-09-18 23:48
Sorry, but I'm not understanding what the issue is here.
What do you mean by `the underground is a mess like vanilla`, and `ravine generation behaves like rtg doesn't exist`?

If you are using `B:"Enable Caves"=false` then caves should be completely disabled in RTG unless you have also set `B:"Enable Cave Modifications"=false`, in which case vanilla caves will generate regardless of the `B:"Enable Caves"` setting. To prevent any caves from being generated, you should use the combination of `B:"Enable Cave Modifications"=true` + `B:"Enable Caves"=false`. (Not very intuitive, to be honest.)

The same goes for ravines, `B:"Enable Ravine Modifications"` should be set to `true` if you want to change their generation. (Note: Ravines are disabled by default.)

If you are using any mods that alter cave or ravine generation (through Forge's `InitMapGenEvent` event), then RTG's settings will have no effect.


For the next release we are moving towards using generator settings in the Customize World Screen, (or the `generator-settings` string of the `server.properties` file for a dedicated server,) to control cave and ravine generation, and the config settings will be removed. Because of this, this issue has no relevance.

**Closed as completed by srs-bsns** 2017-09-18 23:48 UTC
Labels: bug, 1.10, invalid

**Comment by touhouzun** [comment] 2017-09-19 00:13
Sorry,but I really did "Enable Cave Modifications"=true" and "Enable Caves"=false" combination all the time when rtg and heatandclimate are installed.Also "Enable Ravine Modifications=true" and "Enable Ravines=false" default combination.
Just no screenshots no clues,right?Maybe heatandclimate alters cave or ravine generation (through Forge's InitMapGenEvent event) like what you say.However I'm not a programmer and I have no clue.

**Comment by touhouzun** [comment] 2017-09-19 00:27
![1](https://user-images.githubusercontent.com/31458903/30570385-8b164d04-9d13-11e7-83da-6667cadd6731.PNG)
![2](https://user-images.githubusercontent.com/31458903/30570387-8f9aa384-9d13-11e7-8b27-1a199feaa3c2.PNG)
These two are my configs of caves and ravines.
![2017-09-18_20 36 13](https://user-images.githubusercontent.com/31458903/30570404-b2586d8e-9d13-11e7-8de4-174ab987aced.png)
![2017-09-18_20 36 16](https://user-images.githubusercontent.com/31458903/30570407-b9a6829c-9d13-11e7-9808-e29a2792fd89.png)
![2017-09-18_20 36 19](https://user-images.githubusercontent.com/31458903/30570411-c0242f2a-9d13-11e7-919c-6e8d7e4ffc0d.png)
These three shows the effect with only rtg and those two configs.
![2017-09-18_20 40 56](https://user-images.githubusercontent.com/31458903/30570449-00cda2f4-9d14-11e7-8459-771ba8e1683a.png)
![2017-09-18_20 41 00](https://user-images.githubusercontent.com/31458903/30570456-091aee1c-9d14-11e7-9ae8-7edebdf0164a.png)
![2017-09-18_20 41 06](https://user-images.githubusercontent.com/31458903/30570463-0fc8128a-9d14-11e7-8553-a35ad2c80214.png)
![2017-09-18_20 41 09](https://user-images.githubusercontent.com/31458903/30570468-15c465c6-9d14-11e7-8285-c1222028918c.png)
These four shows the effect with rtg and heatandclimate and those two configs.
I have finally realised that screenshots uploading never fails.Those pictures are just urls.

**Comment by touhouzun** [comment] 2017-09-19 02:04
Please anyone here?It's my fault.
