### ISSUE TITLE
crash with BOP 2.1.0.1465

### ISSUE THREAD

**Issue by sircrimer** [Team-RTG/Realistic-Terrain-Generation#296] opened 2015-11-25 21:10 UTC
http://pastebin.com/sTrbCPgP

**Comment by whichonespink44** [comment] 2015-11-25 22:18
@sircrimer Do you happen to remember which biome you were in when it crashed? Are you able to log back into the world?

I've tried reproducing this with BOP 2.1.0.1465, but village generation seems to be working fine.

**Comment by whichonespink44** [comment] 2015-11-25 22:25
Actually... I just noticed that you're using Forge 10.13.4.1558... can you try using 10.13.4.1448 and let me know if it still crashes?

**Comment by Adaptivity** [comment] 2015-11-27 10:00
@whichonespink44 can confirm this crash. Happens when you choose BoP world generator type. No crash with RTG world type. Forge 1492

**Comment by whichonespink44** [comment] 2015-11-27 12:13
It never occurred to me that it might be because of the wrong world type being selected - nice one!

**Comment by Ezoteric** [comment] 2015-11-27 12:22
But shouldn't RTG do nothing when not set to world type?

**Comment by sircrimer** [comment] 2015-11-27 12:32
yes i had BOP world type set. But i agree that this should not happen.

**Comment by whichonespink44** [comment] 2015-11-27 16:19
I suppose I could try to throw an exception if the 'Realistic' world type isn't chosen, similar to the way the game notifies you if you're missing a required mod.

I'd rather not have RTG just 'do nothing' if the Realistic world type isn't chosen though... that's kinda like asking Thaumcraft 'do nothing' if it's installed. If you want Thaumcraft to do nothing, then you remove Thaumcraft... same should apply for RTG - if you're not going to choose the Realistic world type, then remove RTG.

**Comment by Adaptivity** [comment] 2015-11-27 16:26
Hmm, what if someone who plays with RTG world type on main world, want to test something with BoP world type on different world? Seems reasonable enough. But if this really hard to fix, well at least RTG should avoid crashes.

**Comment by whichonespink44** [comment] 2015-11-27 16:31
Fair enough - I'll see what I can do.. hopefully it's just a case of checking the world type during preInit() and preventing any other code from executing if the Realistic world type hasn't been chosen.

**Comment by whichonespink44** [comment] 2015-11-28 11:15
Fixed in fe5e4f4.

**Closed by whichonespink44** 2015-11-28 11:15 UTC
Labels: confirmed, crash

**Comment by Adaptivity** [comment] 2015-11-28 14:59
Good job @whichonespink44! :+1:
