### ISSUE TITLE
RTG trees replace non-air blocks when growing

### ISSUE THREAD

**Issue by garantiertnicht** [Team-RTG/Realistic-Terrain-Generation#1005] opened 2016-10-22 15:33 UTC
##### Affected Mod Versions:
- Forge version: 12.18.2.2107
- RTG version: 4.1.1.2
##### Issue Description:

RTG Oak Trees will replace Blocks while growing, possibly other trees too.

![2016-10-22_17 26 24](https://cloud.githubusercontent.com/assets/7950273/19620414/30739f14-987d-11e6-9097-2f79894d46a3.png)
![2016-10-22_17 27 43](https://cloud.githubusercontent.com/assets/7950273/19620415/32d9fa82-987d-11e6-8744-50ab7905f007.png)
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Go to Extreme Hills
2. Plant an Oak Sapling
3. Place some blocks around the Sapling, maybe some above
4. Use Bonemeal / Tourcherino / Wait a few minutes and hope you get an RTG Tree

**Comment by whichonespink44** [comment] 2016-10-22 15:37
I can confirm that this is definitely an issue with almost every single RTG tree.

Most trees do air checking for the leaves, but none check for air blocks when placing the logs.

My initial thinking is that logs should only check for air blocks when the tree is being generated from a sapling to reduce the extra overhead from world generation.

**Comment by whichonespink44** [comment] 2016-10-29 00:34
Fixed for 1.10.2 in 098d591

**Comment by The-Arcanian** [comment] 2016-11-02 01:30
Was just coming to report this due to it breaking the Botania tree farm I was trying to set up in a Plains biome. Good to a fix is already in the pipeline.

**Comment by whichonespink44** [comment] 2016-11-02 01:41
@The-Arcanian This is fixed in the 4.1.1.5 version for 1.10.2... are you on a different MC version?

**Comment by The-Arcanian** [comment] 2016-11-06 09:47
Well that's a problem.

I am using RTG-1.10.2-4.1.1.5 and it replaces the blocks I place above the sapping if it is growing a Large Oak Tree in a Plains biome, but there has to be room for a Small Oak Tree to grow. I have not tested any other cases other then that it is at least partially biome specific, because it did not happen when I accidentally tried testing it in a Sunflower Plains.

Also before testing this in creative I tried to use Birch in my play word and was getting Large Birch Trees with the same block replace effect. Did you guys add those?

**Comment by whichonespink44** [comment] 2016-11-06 12:59
@The-Arcanian We've added some block-checking above the sapling (Y-axis only) before the tree tries to generate. If there's nothing in the way, up to the height of the tree, it will generate. If it finds any non-air block along the way, it won't.

This isn't an ideal solution, but hopefully it will give you some options when designing your tree farms.

Also, for reference, be sure to remember the following (some might be obvious, but including to be thorough):
1. "RTG trees" are different than "vanilla trees"
2. Saplings can only grow into an RTG tree if the biome naturally generates a tree that drops the sapling that is placed. For example, if you place a spruce sapling in a Plains biome, no RTG trees will generate because the only RTG trees that naturally generate in Plains are the large Oak (which drops an oak sapling) and the large Birch (which drops a birch sapling). Unfortunately, there isn't a master list of all the RTG trees and the biomes in which they generate, but we'll try to get something put together in the future.
3. When an RTG tree grows from a sapling, it doesn't replace any blocks that it's not allowed to... but sometimes it will grow **around** the blocks, making it look like it replaced them.
4. If RTG trees still aren't behaving as you'd like them to, you can disable them in the configs by setting `B:"Enable RTG Saplings"=false`

The new block-checking functionality will be in version 4.1.1.6 when it's released later today. Let me know how it works out for you.

**Comment by The-Arcanian** [comment] 2016-11-08 03:06
Ok, it is fixed now it seams. To try and state more clearly; the problem was when trying to grow Oak or Birch in a Plains biome there appeared to only be a Y check up to the what was required for RTG's equivalent to Vanilla's Small Trees, therefor no tree would grow if there was a block low enough. But if there were no blocks to prevent a small tree, then the RTG equivalent to a Vanilla Big Tree would often grow, replacing any blocks where it wanted to place a wood block (leaves did not replace).

But like I said 4.1.1.6 seams to have fixed it, I am no longer getting what looks like Vanilla Large Trees growing through the blocks that I place above the saplings.

**Comment by Eufranio** [comment] 2016-11-23 18:14
Is it fixed in 1.7?

**Comment by whichonespink44** [comment] 2016-11-23 18:42
Not yet - we're hoping to release an update for 1.7.10 on Sunday - if we do, this will get fixed as part of the update.

**Comment by xenoflot** [comment] 2016-11-28 23:57
Not sure if this is the right place... I've found that trees created during worldgen don't make these checks and are placed after villages are placed. The result being village houses with wood and leaf blocks where there should be stone and other materials.

Running rtg 1.10.2-4.1.1.8

Cheers!

**Comment by srs-bsns** [comment] 2016-11-29 00:16
@xenoflot
>Not sure if this is the right place

No, this is a different issue, and @whichonespink44 added checks in RTG a long time ago to prevent what you are describing, atleast with respect to RTG generated trees. If you are seeing trees growing into village structures, then they are likely non-RTG tree and it is coming from the vanilla biome decorator, or another mod's biome decorator.

If you still feel that it is RTG's trees generating in/on village structures, please open a new issue.

**Comment by xenoflot** [comment] 2016-11-29 00:56
Perfect, thanks. Further isolation testing shows that it's Recurrent Complex' trees.

**Comment by whichonespink44** [comment] 2017-01-31 19:57
Fixed for 1.8.9 in 385020f

**Comment by whichonespink44** [comment] 2017-02-03 00:01
Fixed for 1.7.10 in 7e6daf9

**Closed as completed by whichonespink44** 2017-02-03 00:01 UTC
Labels: bug, confirmed, 1.7
