### ISSUE TITLE
Crash  during SaplingGrowEvent.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [Team-RTG/Realistic-Terrain-Generation#896] opened 2016-08-15 07:10 UTC
##### Affected Mod Versions:
- Forge version:  1.8.9 - 11.15.1.1722 
- RTG version:  RTG-1.8.9-1.0.0-snapshot-2 
- Restricted Saplings: RestrictedSaplings-1.8.9-1.1.0.jar
##### Issue Description:

Server just randomly crashes with exception, see crashlog below.
##### Steps to reproduce the issue: (If it's easily reproducible.)

The server seemed to crash randomly, might have to do something with sapling growth, might have something to do with [Restricted Saplings](https://mods.curse.com/mc-mods/minecraft/232166-restricted-saplings#t1:description)?
##### Extra Information:

[Chrashlog](https://gist.github.com/TheOnlySilverClaw/80e78278a8aa7ecb4029e245112f795b)

**Comment by srs-bsns** [comment] 2016-08-15 15:34
Uhh.. why is a dead bush triggering a SaplingGrowTreeEvent? WTH Forge.

Need to insert a check for this here, and `return`. Is there more than just a `dead bush` non-sapling that can trigger this event?
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.8.9-dev/src/main/java/rtg/event/EventManagerRTG.java#L269-L270

**Comment by TheOnlySilverClaw** [comment] 2016-08-15 15:49
Welll, from the description of Restricted Saplings: "When a sapling is about to grow into a tree (from nature, or from bonemeal, or any source) it first checks the biome.  If the sapling is growing in a biome that does not natively spawn those trees, the growth is blocked, and it is turned into a Dead Bush."

Not sure what exactly the chain of events is in this case,  but maybe that's where that comes from?

**Comment by whichonespink44** [comment] 2016-08-15 19:05
Hmm, I've been unable to reproduce this, bonemealing many combinations of saplings in various biomes, and each time the sapling just turns into a dead bush and drops the sapling that was planted. I even tried bonemealing the dead bush - still no crash.

I'll still put the check in to make sure we're dealing with a proper sapling, so at least the random crash should stop happening.

**Comment by whichonespink44** [comment] 2016-08-16 06:51
Fixed in a6431cf and will be in the next snapshot release.

**Closed as completed by whichonespink44** 2016-08-16 06:51 UTC
Labels: bug: unconfirmed
