### ISSUE TITLE
Server hangs when Tough As Nails is installed

### ISSUE THREAD

**Issue by taluseve** [Team-RTG/Realistic-Terrain-Generation#918] opened 2016-08-22 19:24 UTC
##### Affected Mod Versions:1.10.2

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version:2056
- RTG version:1.10.2
##### Issue Description:RTG wont make server startup with tougher than nails mod that BOP made.

(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
##### Steps to reproduce the issue: (If it's easily reproducible.)

1.
2.
3.
##### Extra Information:togher than nails works with BOP because it's BOP's mod but RTG cant start server with togher than nails and I really enjoy that feature, makes the game more interesting. any chance you could make it compatible?
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by taluseve** [comment] 2016-08-22 19:25
togher= tougher than nails, sorry laptop sucks

**Comment by whichonespink44** [comment] 2016-08-22 20:02
Thanks for reporting. Could you post your fml-client-latest.log file please?

**Comment by whichonespink44** [comment] 2016-08-22 21:36
I'm unable to reproduce this problem using the latest snapshot: https://minecraft.curseforge.com/projects/realistic-terrain-generation/files/2325679

@taluseve I'm closing this, but try downloading the latest snapshot linked above, and if you're still experiencing this issue, post your fml-client-latest.log file and I'll re-open this and investigate further.

**Closed as completed by whichonespink44** 2016-08-22 21:36 UTC
Labels: bug, bug: unconfirmed, 1.10
