### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#298] opened 2015-11-27 15:05 UTC
http://pastebin.com/Kmb3CF3m

I came to the village and crash. RTG-1.7.10-0.0.19

`mineshafts {
    #  [default: true]
    B:"Generate Mineshafts"=true
}`

**Comment by whichonespink44** [comment] 2015-11-27 16:12
Just posting this here for reference for now:

https://github.com/EnviroMine/EnviroMine-1.7/issues/134

Need to look into it further to figure out what's going on.

**Comment by whichonespink44** [comment] 2015-11-28 12:29
I've just tested this using the latest dev version and couldn't reproduce it, so I'm hoping the recent tweaks to the village code have resolved it.

Could you try using [this snapshot](https://goo.gl/RvTY70) and let me know if you still experience the issue?

**Comment by whichonespink44** [comment] 2015-11-28 16:09
@Tsyklop I'm closing this for now, but if it's still happening for you, just let me know and I'll re-open.

**Closed by whichonespink44** 2015-11-28 16:09 UTC
Labels: bug, investigating, unconfirmed
