### ISSUE TITLE
A plethora of bugs on 1.7.10

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#817] opened 2016-07-06 13:22 UTC
Not 100% sure if this is related to Thermos, but I will post it here anyways.

http://pastebin.com/yPdT4XD3

This error happened while using a plugin to autogenerate the world.

Also, I'm finding crap like this:

https://www.dropbox.com/s/qri1ni6no7xbbj9/Screenshot%202016-07-06%2009.30.12.png?dl=0

The only workaround is to clear the configs, but then it comes back eventually. (This also happens in singleplayer. A good way to get this is to clear the RTG folder on an existing world.)

Edit: Are trees supposed to generate like this? https://www.dropbox.com/s/9xrjraeoil0ocy5/Screenshot%202016-07-06%2010.04.11.png?dl=0

**Comment by whichonespink44** [comment] 2016-07-06 16:34
We don't support thermos/cauldron/craftbukkit/kcauldron so unless you can reproduce these issues in a Forge-only environment, there's not much we can do, sorry.

**Comment by Sunconure11** [comment] 2016-07-06 16:36
The messing up of generation with old/cleared configs can be replicated in a singleplayer environment. I found it on accident when I was prepping for the next release of my modpack while toying around with singleplayer. It is identical to an issue that has been reported on the MCF regarding cobble rivers and such.

**Comment by srs-bsns** [comment] 2016-07-06 16:38
This shenanigans, I assume, is probably caused by [ptweaks](http://dev.bukkit.org/bukkit-plugins/ptweaks-remove-all-server-lag/) since it manipulates how chunks are loaded and unloaded

**Comment by whichonespink44** [comment] 2016-07-06 16:38
@Sunconure11 So if I create an RTG world, generate some chunks, and then delete the RTG config folder, I should experience the messed up generation?

**Comment by Sunconure11** [comment] 2016-07-06 16:39
Yes.

**Comment by srs-bsns** [comment] 2016-07-06 16:39
Can you reproduce this with just RTG?

**Comment by Sunconure11** [comment] 2016-07-06 16:40
I will try it out.

**Comment by Sunconure11** [comment] 2016-07-06 16:46
Not replicable with only RTG.

The following generation modifying mods are present in my pack (I probably missed one or two):

BiomeTweaker (only using it as an overglorified mod spawner)
Recurrent Complex
Climate Control
Streams
WildCaves3
Fossils and Archaeology
Biomes O' Plenty
Growthcraft
Thaumcraft
Ars Magica 2
COFHCore
Apple Milk Tea 2
Doomlike Dungeons
Roguelike Dungeons
Primitive Mobs
Plant Mega Pack
Dungeon Mobs
Lycanites Mobs

**Comment by Sunconure11** [comment] 2016-07-06 17:12
This is what the streams dev had to say about an issue with wonky generation like this, too.

"Cobblestone river sections generally mean that certain chunks are not being populated (it's a technical term in worldgen that refers to adding trees, villages etc to 16x16 chunks of terrain) . In the world where this happens, do you see square patches of ground with little vegetation compared to their surroundings? I know this was an issue with earlier versions of RTG, not sure if there was a regression in their latest release.

Another common symptom of unpopulated chunks is chopped-off villages; it happened in RTG before (https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/686) and seems to sometimes happen in vanilla still (https://github.com/MinecraftForge/MinecraftForge/issues/3020)."

**Comment by srs-bsns** [comment] 2016-07-06 17:26
> This is what the streams dev had to say about an issue with wonky generation like this, too.
> 
> "Cobblestone river sections generally mean that certain chunks are not being populated (it's a technical term in worldgen that refers to adding trees, villages etc to 16x16 chunks of terrain) . In the world where this happens, do you see square patches of ground with little vegetation compared to their surroundings? I know this was an issue with earlier versions of RTG, not sure if there was a regression in their latest release.

This was already brought up before on MCF [comment #3047](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3047). It is unlikely that this is an RTG issue.

> Another common symptom of unpopulated chunks is chopped-off villages; it happened in RTG before (#686) and seems to sometimes happen in vanilla still (MinecraftForge/MinecraftForge#3020"

That is a vanilla bug. There is an open PR to fix this in Forge, but it will only be applicable to 1.10.2 and onwards, if and when it gets merged. It's unlikely we can do anything about it for previous versions of MC.

**Comment by whichonespink44** [comment] 2016-07-06 18:28
Yeah, I'm gonna close this as I wasn't able to reproduce the warped generation from deleting the RTG config folder, and all of that other stuff is almost certainly not being caused by RTG.

@Sunconure11 If you can reproduce any of the issues above with a smaller set of mods, in a Forge-only environment, then we'll re-open this issue. Wish there was more we could do, sorry.

**Closed as completed by whichonespink44** 2016-07-06 18:28 UTC
Labels: unsupported
