### ISSUE TITLE
Square snow pattern on Streams

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#1030] opened 2016-11-06 13:51 UTC
##### Affected Mod Versions:
- Forge version: 1.10.2-12.18.2.2120
- RTG version: 4.1.1.5
- GeographiCraft version: 0.7.5
- Streams / Farseek version: 0.2.1 / 1.1
- Biomes O' Plenty version: 5.0.0.2091

##### Issue Description:
I found an apparent square snow pattern on streams in an Ice Mountains biome.

![2016-11-06_14 35 37](https://cloud.githubusercontent.com/assets/22047030/20038147/b6084866-a42e-11e6-8679-4d4dee755549.png)

Seed: -4304547433725488807
XYZ: -708 / 120 / -257

##### Steps to reproduce the issue:
1. Install RTG with GeographiCraft and Streams.
2. Generate a RTG world.
3. Find a snowy biome with a stream in it.

**Comment by whichonespink44** [comment] 2016-11-06 14:23
Thanks for the comprehensive report - we'll try to reproduce this in our development environment and see if we can figure out what's going on.

**Comment by ghost** [comment] 2016-11-06 14:43
If it makes any difference (for reproducing with given seed), set B:SeparateLandmasses=false in geographicraft.cfg.

**Comment by whichonespink44** [comment] 2016-11-06 15:09
That will definitely make a difference, thanks.

**Comment by Sunconure11** [comment] 2016-11-06 23:10
Encountered this on 1.7.10 when I had streams before I decided to pull it from my pack. I think it might be an issue with streams itself, rather than RTG.

**Comment by srs-bsns** [comment] 2016-11-07 03:26
It could actually be another mod that is interacting badly with the way Streams generates it's streams, which is during the biome decoration process. There have been issues in the past with mods DENYing decoration events which prevents Streams from finishing what it's doing. (MagiaNaturalis in 1.7.10, See #870). However, the nature of these strips doesn't quite fit that, and it's also strange that they are all 8 blocks wide.

@mankra Can we get a full mod list, please. And is this in a dedicated server environment? If Yes, is there a plugin manager in use? (Bukkit/Thermos, etc..)

**Comment by ghost** [comment] 2016-11-07 07:58
Here's the mod list. It's my private modpack which also runs on a dedicated server where I use [MSM](http://msmhq.com). No Bukkit etc.

Edit: I reduced the list to the necessary mods, updated to the latest version and can confirm that the pattern is still generating at given coordinates.
- Biomes O' Plenty 5.0.0.2093
- Farseek 1.1
- GeographiCraft 0.7.6
- Realistic Terrain Generation 4.1.1.6
- Streams 0.2.1

**Comment by whichonespink44** [comment] 2016-11-08 14:46
After looking at those screenshots a bit closer, it reminds me of the issue Streams used to have with the stone bridges that would generate perpendicular to the stream.

**Comment by ghost** [comment] 2016-11-09 13:37
Please note the edit in my modlist post.

**Comment by srs-bsns** [comment] 2016-11-09 14:20
I can't reproduce this world. Are you using modified config settings in GeographiCraft?

![2016-11-09_09 17 15](https://cloud.githubusercontent.com/assets/8453133/20141277/97e95948-a65d-11e6-8387-e582953627f6.png)

**Comment by ghost** [comment] 2016-11-09 15:45
B:SeparateLandmasses=false in geographicraft.cfg

**Comment by srs-bsns** [comment] 2016-11-09 18:25
@delvr

This is only happening where there are streams, nowhere else.
The strips coincide with chunk borders.
This is likely from a bad iteration in the Streams decorator?

![2016-11-09_13 19 02](https://cloud.githubusercontent.com/assets/8453133/20149434/395f8362-a67f-11e6-9ba3-790a0a4b667c.png)
![2016-11-09_13 06 31](https://cloud.githubusercontent.com/assets/8453133/20149435/3b3ef2a8-a67f-11e6-96ef-8ae194b518fb.png)

**Comment by delvr** [comment] 2016-11-10 21:25
Thanks for letting me know, I'll take a look on my end.

**Comment by delvr** [comment] 2016-11-27 18:50
OK this should be fixed in the new Streams 0.3/Farseek 2.0 version. Please give it a try and let me know of any issues, thanks!

**Closed as completed** 2016-11-27 18:55 UTC
Labels: bug, confirmed, bug: other, 1.10

**Comment by whichonespink44** [comment] 2016-11-27 22:08
@delvr Just tested a few snowy seeds with the latest versions of RTG, Streams & Farseek and didn't see this issue at all, so hopefully @mankra can confirm it's working on his side too.

Nice work on the SpongeForge compatibility by the way! 👍

**Comment by ghost** [comment] 2016-11-29 08:43
Fix confirmed. Thanks a lot! :-)

**Comment by keybounce** [comment] 2017-02-11 10:32
Streams 0.3?!? When/where was that released?

**Comment by srs-bsns** [comment] 2017-02-11 10:55
https://minecraft.curseforge.com/projects/streams/files

**Comment by keybounce** [comment] 2017-02-11 16:47
Ahh. OK, is there a 0.3 for 1.7.10? I did not see it
EDIT: Never mind, this is not the Streams thread, this is an RTG thread.
