### ISSUE TITLE
Chromaticraft biomes don't generate with BOP installed

### ISSUE THREAD

**Issue by Haggle1996** [Team-RTG/Realistic-Terrain-Generation#314] opened 2015-12-04 06:37 UTC
With both Biomes O'Plenty and ChromatiCraft installed, Chromaticraft Biomes (Rainbow and Ender Forest) do not seem to spawn. I've pregenerated several worlds now with a radius of 100 chunks (200x200 chunks generated per world), and the CC biomes do not appear in any of them. Is there something that needs to be done to enable CC biomes to spawn alongside BOP? Or am I just unlucky after generating 120,000+ chunks?

**Comment by whichonespink44** [comment] 2015-12-04 07:11
Hmm... have you checked the biome IDs in each mod's relevant config file? It sounds like there's a biome ID conflict. Another way to check is to do a biome dump using NEI (Options > Tools > Dumps) and see if the CC biomes are being registered. If there's an ID conflict, they won't show up in that dump.

If there's no ID conflict, then make sure [these values](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/config/RTG/biomes/chromaticraft.cfg#L6-L15) are set to TRUE, and [these values](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/config/RTG/biomes/chromaticraft.cfg#L30-L33) are between 1-20 (a value of 0 disables them)

**Comment by whichonespink44** [comment] 2015-12-04 07:14
If everything checks out, it could just be that you're unlucky... to see if that's the case, try increasing the weights of the CC biomes to `20` and setting the `biome size` to `5` in _[rtg.cfg](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/config/RTG/rtg.cfg#L16)_ and see if that helps.

**Comment by Haggle1996** [comment] 2015-12-04 16:59
I will test this tonight and report back.

**Comment by Haggle1996** [comment] 2015-12-05 00:52
I suppose I could just be really unlucky. I verified the CC biomes are registered, and that there are no conflicts between BoP and CC. I verified the CC biomes are set to generate, and increased their weights to 20. For kicks and giggles, after I didn't get any CC biomes in the first test, I reduced the biome size from 5 to 1 (because I got gigantic biomes instead of many different ones and then reduced the BoP weights to 1. Ran a couple of large tests -- still no CC biomes. Not sure what is happening, but they just don't seem to want to populate.

**Comment by Haggle1996** [comment] 2015-12-05 01:05
Setting the 'Generate just this biome' option to the Rainbow Forest did create a rainbow forest.

**Comment by whichonespink44** [comment] 2015-12-05 03:55
Hmmm... I'll generate a few worlds now to see if I can get them to generate.

**Comment by whichonespink44** [comment] 2015-12-05 04:34
RTG 0.1.0
DragonAPI v9b
ChromatiCraft v9b
Default configs
First world I generated... started at 0,0 (ish) and teleported in 1,000 block increments in every direction...

![Rainbow Forest](http://i.imgur.com/Cpu4pak.png)

![EnderForest](http://i.imgur.com/38jtEqR.png)

Heh, just noticed that I actually found an Ender Forest bordering a Rainbow Forest... if you look at the first screenshot, the biome says Ender Forest!! When I backed up to take the screenshot in the Rainbow Forest, I must've stumbled into an Ender Forest and didn't even realise it!!! :smile: 

So yeah man... I think you've just been incredibly unlucky!!! I would recommend following the steps above and try teleporting 1,000 blocks in every direction starting from 0,0 to see if you can find them.

If you can't... send me your entire config folder and a list of mods (fml-client-latest.log would be perfect) and I'll see if I can spot anything weird.

**Comment by Haggle1996** [comment] 2015-12-05 15:34
I didn't see Biomes O' Plenty in your list. CC biomes generate fine without BoP installed. It could very well be a mod interaction on my part -- Revolution is a pretty big pack. I'll do a bit more poking and update this thread or close it if I discover anything.

**Comment by whichonespink44** [comment] 2015-12-05 15:44
Doh! How embarrassing - I totally forgot to add BOP!! I'll do another test as well and let you know.

**Comment by whichonespink44** [comment] 2015-12-05 17:35
I haven't found any CC biomes, and I've covered a LOT of ground... even tweaked the configs, still nothing... I'll put this down as a confirmed bug and look into it more when I can.

I suspect it might have something to do with the current memory issue, because as I was TP'ing around the world, I often had to shutdown MC because I ran out of memory, something that's not really happened before during my testing... Maybe a weird interation bug with RTG+BOP+CC or maybe just a BOP+CC thing?

@Haggle1996 Let me know how you get on.

**Comment by Haggle1996** [comment] 2015-12-05 17:56
I can confirm the memory issue -- it's what's holding me back from including RTG as a recommended mod in my pack (and I REALLY want RTG in my pack). I do not encounter the memory issue with just BOP+CC, only with BOP+CC+RTG. 

In particular, the memory problem gets significantly worse when there are tall biomes, like Alps, getting generated. I recall one test world with two Alps biomes next to each other, split by a river, which exhausted in seconds the 12GB I had allocated.

**Comment by whichonespink44** [comment] 2015-12-05 18:23
Well, the memory issue will hopefully be radically improved with tomorrow's update. I've been reading up on Java performance best practices, and... well... let's just say that my practices aren't currently the best!! :stuck_out_tongue_winking_eye: I've identified a portion of code that's almost certainly the major cause of most of the memory issues with RTG on its own. No whether that will alleviate the issues with BOP + CC, I guess we'll soon find out!

**Comment by Haggle1996** [comment] 2015-12-07 03:44
Just an update. Reran the battery of world generation with 0.2.0, using 4 pregenerated worlds of 40,000 chunks each. Still no CC biomes to be found. The memory issue is better -- seems to take twice as long to run out of memory, so cheers there. A lot more instances of cut off terrain, particularly trees crossing chunk borders are sheared off.

**Comment by whichonespink44** [comment] 2015-12-07 12:00
Glad to hear the performance is better, but I'm concerned about this 'cut off terrain' that you mentioned. I'm assuming this occurred with newly-generated worlds?

Would you be able to post some screenshots, preferably with the  F3 screen on?

**Comment by Haggle1996** [comment] 2015-12-07 14:34
http://imgur.com/a/ckQPB

**Comment by whichonespink44** [comment] 2015-12-07 15:19
Thanks for those... have you noticed any other trees getting cut off? Just wondering if it might be a bug with that particular tree.

To be honest, I don't see how it could be an RTG thing, as nothing I changed in the latest version would affect that sort of thing, not even the memory tweaks that I made. Very bizarre!

In addition to any other screenshots you think are worth sharing, could you share your `fml-client-latest.log` file when you get a chance?

**Comment by Ezoteric** [comment] 2015-12-07 15:53
I have not seen a cut off tree in my world

**Comment by whichonespink44** [comment] 2015-12-14 22:06
@Haggle1996 I have some findings to report... it seems that changing BOP's conflicting biome IDs allows CC biomes to generate, but changing CC's conflicting biome IDs does not. Previously, I was changing CC's biome IDs to resolve the initial conflict, but then on a hunch I tried changing BOP's IDs instead:

~~I:"Canyon ID"=47~~ - I:"Canyon ID"=**247**
~~I:"Chaparral ID"=48~~ - I:"Chaparral ID"=**248**

It would seem that either RTG is doing something bizarre behind the scenes, or CC has somehow hardcoded its biome IDs somewhere. I'll need to keep investigating to know for sure.

This was using RTG 0.3.0 and CC v9b.

Do you want to pre-gen a few worlds and let me know it's working for you? (You might want to reduce biome size to 2 and/or increase the weights of the CC biomes to make testing easier.)

Let me know how you get on.

**Comment by Haggle1996** [comment] 2015-12-15 04:02
I'll give it a whirl with 0.3. Just FYI, in my scenario, I had changed the BoP biomes instead of the CC ones previously with earlier versions.

**Comment by whichonespink44** [comment] 2015-12-15 07:26
Hmmm, very bizarre. I'm wondering if it's all been just a case of bad luck.

I've just done more testing, this time the only thing I changed from the default configs (besides the IDs) was boosting the CC biome weights to 100, and I found both Ender Forest and Rainbow Forest in this seed:

-7823907384391564939

So that's with RTG 0.3.0, BOP 2.1.0.1465, CC V9b & DragonAPI V9b, and a few utility mods.

BOP conflicting IDs changed to:

I:"Canyon ID"=247
I:"Chaparral ID"=248

And all other config settings left on defaults.

I'm just about to try the same seed again with default biome weights - I'll let you know how it goes.

**Comment by whichonespink44** [comment] 2015-12-15 10:08
Ok, using that seed with the default weights didn't result in any CC biomes, but I was wrong about needing to change the BOP biome IDs because I tried that same seed and changed the CC biome IDs and got the exact same map as before, with both Ender Forest and Rainbow Forest.

I'm going to try a few more seeds with the default settings and see if I can get lucky.

**Comment by whichonespink44** [comment] 2015-12-15 10:53
Success!!

Try this seed:

-8806489635512525182

Everything using default configs (except resolved biome ID conflicts)

Rainbow Forest at 1200 / -1500

Ender Forest at 1500 / -500

So either the bug was fixed somehow in 0.3.0 or we were both incredibly unlucky!! :)

Closing for now, but feel free to re-open if still not working for you.

**Closed by whichonespink44** 2015-12-15 10:53 UTC
Labels: 0.4.0, bug, confirmed

**Comment by Haggle1996** [comment] 2015-12-15 21:44
I can find them now; however, new issue reported with a different Reika's mod. :P
