### ISSUE TITLE
Wrong Biomes Generating

### ISSUE THREAD

**Issue by Haggle1996** [Team-RTG/Realistic-Terrain-Generation#439] opened 2016-01-23 01:56 UTC
With RC2, ocean biome types are generating inland. This isn't the only example.

![2016-01-22_18 53 38](https://cloud.githubusercontent.com/assets/11808184/12527505/c76a81a6-c139-11e5-97a0-7b660da4aa5d.png)

**Comment by Haggle1996** [comment] 2016-01-23 01:57
![2016-01-22_18 57 04](https://cloud.githubusercontent.com/assets/11808184/12527515/fa4257fc-c139-11e5-83bb-fe8004b3f3b6.png)

Apparently, I've terraformed the moon.

**Comment by whichonespink44** [comment] 2016-01-23 08:33
That's bizarre... have you confirmed there are no biome ID conflicts? If there are no conflicts, would you be able to post a recent fml-client-latest.log file so we can have a look?

**Comment by Adaptivity** [comment] 2016-01-23 11:34
@Haggle1996 can you check if moon biome id lower than 127?

**Comment by Haggle1996** [comment] 2016-01-23 16:30
No conflicts; I double checked after I saw the moon biome, as strange biomes in the overworld is usually a sign of a conflict. They're happening very frequently, as if there's no dimension ID restriction on biomes. The strange biomes aren't decorated as they would in their proper dimension, and, as you can see from above, other than Botania flowers, the biome doesn't decorate (probably because you don't have a config for them. :P )

[fml-client-latest.zip](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/101931/fml-client-latest.zip)

The moon biome ID is much lower than 127...it's -28.

**Comment by Zeno410** [comment] 2016-01-23 17:06
This may be a long-standing bug I finally caught Thursday. The CC river routine was occasionally putting in random biomes (due to a typo referencing the wrong value).

**Comment by whichonespink44** [comment] 2016-01-29 20:34
@Haggle1996 Has the [beta39 version of CC](https://www.dropbox.com/s/q0vo7477x4vk7wf/ClimateControl-0.4.beta39.jar?dl=0) resolved this issue?

**Comment by Haggle1996** [comment] 2016-01-30 16:55
I have not found any _really_ wrong biomes, like the moon generating in the overworld. So it's probably safe to close this issue. 

I note that I still see wrong biomes only on what I presume are Islands. Continents seem to be perfect. By wrong biome, I mean Kelp Forests, Coral Reefs, and Oceans. In the below image is a typical island. The green areas are flagged as Coral Reefs, the stone area is marked 'Beach', and the upper elevations of sand are 'Ocean'. The bands of sand around the island are correctly marked 'Beach'. 
![image](https://cloud.githubusercontent.com/assets/11808184/12697068/031357ca-c737-11e5-9cf3-607cc8374978.png)

All things considered, this is probably a minor issue at this point.

**Comment by whichonespink44** [comment] 2016-01-30 17:37
Glad to hear the biomes are generating correctly now. I'll close this as I believe the island issues you pointed out are a known issue with the biome repair system, which we're hoping to improve for 0.5.1.

**Closed by whichonespink44** 2016-01-30 17:37 UTC

**Comment by Zeno410** [comment] 2016-01-30 17:40
This probably is an effect of raising the beaches to try to "protect" the land, which is often very low, which is the primary driver of the oversized beaches with chunky border. In 0.6 I'm planning a more "proper" fix of raising up the low-lying nonswamps and then dropping the beaches back down. This little island is probably an isolated beach, and beaches are high enough to pull shallow ocean above water. In 0.6 the beaches will be lower again and things like this will get smaller or disappear.
