### ISSUE TITLE
Tree Density Adjusting is Not Working

### ISSUE THREAD

**Issue by CacheTellsStories** [Team-RTG/Realistic-Terrain-Generation#1327] opened 2019-09-28 06:52 UTC
I only have biomes o plenty installed in terms of biome mods, and this issue appears to only affect vanilla forests. Anyway, the forest biomes are super dense. So dense they cause extreme lag whenever I point my camera in their direction. I tied adjusting the config file (both the main RTG config and the specific biome ones) nothing worked. In fact, the trees seemed to get more dense. What I did was change the density control number from -1.0 to 0.6. 

The negative is kind of throwing me off, is that what I am doing wrong?

**Comment by srs-bsns** [comment] 2019-10-15 07:18
There has never, in the history of porting RTG to 1.12, been any issues seen or reported by our beta testers concerning tree density.
You haven't provided any tangible info about this issue. (mod list, screenshots, etc..)

This is likely being caused by another mod that is changing the tree density in the biomes native decorator, or is generating trees in an improper manner.
RTGs tree density settings are multipliers, but as the config comments clearly state, it only affects trees that are generated by RTG.
Values < 1.0 will decrease the amount of trees, and values > 1.0 will increase them. The value will not exceed 5.0.
(The negative biome-specific setting means it is disabled, but this was changed in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/1e4437e9c0466dd3712ea3c693222cf5787f505b)
In biomes where the tree density is already somewhat low, this setting may not have much of a noticeable effect.

Regardless, there shouldn't be much of an FPS drop unless there is something else going on, or unless you are maybe using OptiFine with shaders that require ridiculous processing.

I have made a slight alteration to how the multipliers are applied and changed the config comments to hopefully make them more clear. This change will be in the next release.

**Closed as completed by srs-bsns** 2019-10-15 07:18 UTC
Labels: question, 1.12
