### ISSUE TITLE
Sunflowers does not generate in sunflower plains 

### ISSUE THREAD

**Issue by ComfyFluffy** [Team-RTG/Realistic-Terrain-Generation#1217] opened 2017-07-30 10:32 UTC
##### Affected Mod Versions:
- Forge version:1.10.2-12.18.3.2422
- RTG version:1.10.2-4.2.0.0-snapshot-5

##### Issue Description:
![2017-07-30_18 23 42](https://user-images.githubusercontent.com/24245520/28752537-f5f0a85e-7554-11e7-9fb0-0f16519bec7c.png)
![2017-07-30_18 25 19](https://user-images.githubusercontent.com/24245520/28752538-f60c1954-7554-11e7-835a-3e1840769bfb.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)
find a sunflower plains

**Comment by whichonespink44** [comment] 2017-09-23 20:30
I'm unable to reproduce this in the latest dev build, so closing this for now.

@Wows233 If it's still in an issue when we release the next snapshot, please let us know.

**Closed as completed by whichonespink44** 2017-09-23 20:30 UTC
Labels: bug, bug: unconfirmed, 1.10
