### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by zack-emmert** [Team-RTG/Realistic-Terrain-Generation#884] opened 2016-08-01 02:09 UTC
##### Affected Mod Versions:
- Forge version: Recommended build for 1.10
- RTG version: 2.0.0-alpha6
- BoP version: 4.1.0
- Other mods versions can be found in the log file
##### Issue Description:

Crashes occasionally with an `Exception ticking world` error. Only correlation between crashes seems to be generating new chunks.
##### Steps to reproduce the issue: (If it's easily reproducible.)

Not easily reproducible
##### Extra Information:

Log File:
[http://pastebin.com/F6DWKBpr](http://pastebin.com/F6DWKBpr)

**Comment by srs-bsns** [comment] 2016-08-01 09:46
Dupe of #866.

**Closed as completed by srs-bsns** 2016-08-01 09:46 UTC
Labels: duplicate
