### ISSUE TITLE
[1.10.2] Ticking World

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-RTG/Realistic-Terrain-Generation#1218] opened 2017-08-02 14:22 UTC
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.10.2-12.18.3.2316
- RTG version: 1.10.2-4.1.2.4
- BoP version: 1.10.2-5.0.0.2236
- BiomeTweaker: 1.10.2-2.3.239
- CoFHCore version: 1.10.2-4.1.9.13

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
The world crashes randomly, with a ticking world exception. It doesn't seem to be caused by an action from the player, as it happens during various different things. I've been having this issue with all versions of RTG in 1.10.2, but it's rare, so I don't mind it much.

##### Steps to reproduce the issue: (If it's easily reproducible.)

It isn't, unfortunately

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

Crashlog: https://pastebin.com/fA45XxHf

**Comment by srs-bsns** [comment] 2017-08-02 14:43
This is a duplicate of #1207.
Update COFHCore to version 1.10.2-4.1.10.14 or newer.

**Closed as completed by srs-bsns** 2017-08-02 14:43 UTC
Labels: duplicate, bug: other

**Comment by NielsPilgaard** [comment] 2017-08-02 18:18
Thank you :)
