### ISSUE TITLE
Chunk X/Z Flipping

### ISSUE THREAD

**Issue by vagaprime** [Team-RTG/Realistic-Terrain-Generation#701] opened 2016-05-12 22:10 UTC
I have been coming across some odd Biome transitions. I have RTG .8RC2, CC 5 beta 53, and BoP 2.1.0.1889.

Screen shots and JM saved Map.
http://imgur.com/a/AHlZ1

**Comment by srs-bsns** [comment] 2016-05-12 23:42
Duplicate of #658, and probably other closed issues. More X/Z flipping. I thought this was fixed, like 5324 times now? :confused:

**Comment by Zeno410** [comment] 2016-05-18 23:44
I've looked all the way around a large Crag with the current dev build, CC-beta55, Forge-1614, and BoP-1889 and I don't see this.

**Comment by vagaprime** [comment] 2016-05-19 05:12
Its not just crag biomes that are going this. I am getting it along Desert border's and beaches.

**Comment by whichonespink44** [comment] 2016-05-19 05:47
@vagaprime Could you post your fml-client-latest.log file via Pastebin so we can look into this further?

**Comment by chaNcharge** [comment] 2016-05-19 05:50
@vagaprime Could you also post the seed and coords where you found the bug so I can try to reproduce this with the dev version I have?

**Comment by Zeno410** [comment] 2016-05-19 20:19
I was looking at Crag because a) it was in your report and b) you can't miss it. No other mods?

**Comment by chaNcharge** [comment] 2016-05-20 00:27
Found something, I used the seed he posted, except I'm not seeing a crag anywhere but I did see this. I highlighted chunk borders also.
![2016-05-19_17 21 35](https://cloud.githubusercontent.com/assets/11594018/15413609/e3330872-1de6-11e6-9a7c-f030aa553a25.png)
![2016-05-19_17 22 13](https://cloud.githubusercontent.com/assets/11594018/15413610/e333fe26-1de6-11e6-94bf-cecca177887e.png)

**Comment by vagaprime** [comment] 2016-05-20 00:30
In order to get the exact same world with that seed that I received you would need to be running the modpack that I am currently working on. I will upload the forge log in a bit, and upload a new dev build and post the link here as well.

**Comment by Zeno410** [comment] 2016-05-20 02:57
You mean the tree without snow? That's a separate issue, related to sequencing of cross-chunk trees. I believe it happens in vanilla too, it's just much rarer and less noticeable since vanilla keeps big trees away from snow.

**Comment by topisani** [comment] 2016-05-20 11:05
if we only use very few of those big trees, we could let them tend to generate in the center of chunks

**Comment by Zeno410** [comment] 2016-05-20 20:13
That's an option for the Ex-Hills trees but not really when Forest/Taiga/Jungle/etc. run close to the border.

**Comment by vagaprime** [comment] 2016-05-22 16:02
Here is the FML Log.

https://drive.google.com/open?id=0B0R2hb2S8d3iNUVrUy1jTEs4T2c

And here is a link to the newsest dev build of my pack as well

https://drive.google.com/open?id=0B0R2hb2S8d3ib2VkQUVlQWloQWs

**Comment by Zeno410** [comment] 2016-05-22 16:51
And we have the cause! Which is Mariculture. Mariculture does X/Z flips if a certain config option is on (almost certainly a bug in Mariculture). See the RTG original post for details.

**Closed by Zeno410** 2016-05-22 16:51 UTC
Labels: bug, unconfirmed, world-gen

**Comment by vagaprime** [comment] 2016-05-22 16:59
Ok thanks.

**Comment by whichonespink44** [comment] 2016-05-22 18:24
This is actually listed in the OP as one of RTG's 'known issues' but it should probably be added as an issue on here as well. There's not much we can do about this one, but I'll try to get in touch with the Mariculture devs to see if there's anything they can do.

**Comment by whichonespink44** [comment] 2016-05-22 18:26
#724
