### ISSUE TITLE
BattleTowers conflict config RTG rc2

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Team-RTG/Realistic-Terrain-Generation#444] opened 2016-01-25 21:08 UTC
using
RPG-1.7.10-0.5.0-RC-2.jar
breaks config file BattleTowers.cfg

biomespawnallowed {
    B:=true
}
there has to be like this:

biomespawnallowed {
    B:DesertHills=true
    B:Ocean=true

because a broken config is not generated map. crash.
RPG-1.7.10-0.4 all ok

log
http://pastebin.ubuntu.com/14666383/

PS
I have another problem, but it seems you have solved it in RC3?
https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/179e762c505b026e029ce4f0d703f2cf159c0092
or am I mistaken?
CC+BOP+ RTG 
creating a new world and 127 files in a folder saves\map\region\

**Comment by SvEgiiVEteR** [comment] 2016-01-28 23:31
I set a new version RTG-1.7.10-0.5.0.jar. the problem remained the world is not generated with BattleTowers-1.7.10.jar... 
the fix would not be? RTG-1.7.10-0.4.0.jar worked

**Comment by whichonespink44** [comment] 2016-01-28 23:59
This is the method that BattleTowers uses to generate the config option:

private boolean getIsBiomeAllowed(BiomeGenBase target)
  {
    if (this.biomesMap.containsKey(target.field_76791_y)) {
      return ((Boolean)this.biomesMap.get(target.field_76791_y)).booleanValue();
    }
    Configuration config = AS_BattleTowersCore.instance.configuration;
    config.load();
    boolean result = config.get("BiomeSpawnAllowed", target.field_76791_y, true).getBoolean(true);
    config.save();
    this.biomesMap.put(target.field_76791_y, Boolean.valueOf(result));
    return result;
  }

It looks like it takes a biome as its only argument, searches the biome map for an obfuscated member of BiomeGenBase, which appears to be 'biomeName', but for some reason it's not finding it.

@Team-RTG/readers Any idea why this would've worked in 0.4 and not in 0.5?

**Comment by Zeno410** [comment] 2016-01-29 02:11
Looks to me that the issue is that getIsBiomeAllowed() isn't even getting called now, so the problem is upstream. That code will leave a line in the config for every biome it's called for.

I believe it's searching its *own* biome map, something internal to BattleTowers. The name is coming out of the BiomeGenBase object.

**Comment by whichonespink44** [comment] 2016-01-29 11:44
@AtomicStryker Any idea what might be happening here? We just recently updated RTG from 0.4 to 0.5, which was a pretty massive update for us, so any insight you could give would go a long way towards helping us track this one down.

**Comment by AtomicStryker** [comment] 2016-01-29 15:47
Well, Battletowers is reading the BiomeGenBase.biomeName field. The only reason why the config would be "empy" like that is when the field has an empty string. Check your biomes, there is atleast one with such a symptom. Of course, i should be checking the validity of that field (seeing as the config crashes when it writes an invalid value) but since this has literally never happened before ... i'd rather you fix the biome.

**Comment by Zeno410** [comment] 2016-01-29 15:50
I papered over an empty biome name coming up and never got around to looking at what's empty.

**Comment by whichonespink44** [comment] 2016-01-29 21:42
Just been debugging this one by dumping biome IDs of the biomes that are getting returned from the biomeCache [here](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/biome/WorldChunkManagerRTG.java#L130), and there are definitely biomes being returned that don't have biome names, but there doesn't seem to be any pattern to the nameless biomes from world to world. Deep Ocean, for example... sometimes it gets pulled from the cache with a name, and sometimes it doesn't. What's really confusing me though is... we're using vanilla biomes... and all of the vanilla biomes have biomeNames... so... how on earth could it be losing it's name?

**Comment by Zeno410** [comment] 2016-01-30 00:03
Is it Realistic biomes that don't set their name from their source biomes?

**Comment by whichonespink44** [comment] 2016-01-30 05:22
Yep, that's exactly what it was.

Fixed in 3e4a874 and will be in the 0.5.1 release.

**Closed by whichonespink44** 2016-01-30 05:22 UTC
Labels: crash
