### ISSUE TITLE
Villages... EVERYWHERE...

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#934] opened 2016-09-01 16:25 UTC
RTG is not adhering to biome restrictions when generating villages, so villages end up generating in Ocean/Deep Ocean, and on beaches, etc..

Only tagged for 1.10.2, but may affect olther versions of RTG.

![2016-08-31_09 54 47](https://cloud.githubusercontent.com/assets/8453133/18175386/1c956e16-703f-11e6-85bf-d46030888dfc.png)

**Comment by whichonespink44** [comment] 2016-09-01 22:35
This will be fixed in the next snapshot for 1.10.2, but we'll need to test other versions to see if it's happening in those as well... I suspect 1.9.4 will have the same problem at least.

**Comment by lightningo7** [comment] 2016-09-05 11:02
1.8.9 does not have this issue.

**Comment by ghost** [comment] 2016-09-10 10:49
I can confirm this for the latest 1.10.2 version, but I like the idea of having a few villages in the ocean. It just looks awkward when the building foundations reach to the ocean floor. Similar problem at mountain sides, but it can also look nice...

Suggestion: Implement rare "simming village", but only if you're able to cut off the foundations. You could also add boats alongside the wood planks.

**Comment by whichonespink44** [comment] 2016-09-12 23:34
Fixed in 51db579 and will be in the next snapshot, scheduled to be released tomorrow (Tuesday) night.

**Comment by srs-bsns** [comment] 2016-09-20 21:29
oops

**Comment by garantiertnicht** [comment] 2016-10-23 12:53
I've got a village in Deep Ocean Biome with Forge 12.18.2.2107 and RTG 4.1.1.2 (Default configuration) at 500/-3660 with seed 7689168507588746723

![2016-10-23_14 52 41](https://cloud.githubusercontent.com/assets/7950273/19626366/621714a2-9930-11e6-8b6c-5dbd764e2aa4.png)

**Comment by whichonespink44** [comment] 2016-10-23 14:13
1.10.2 --- After a Discord debugging session @garantiertnicht was able to determine that it was the Java version (1.8.0_25) that was causing the issue. When using Java 1.8.0_74, the issue went away.

**Comment by whichonespink44** [comment] 2016-10-23 14:17
Closing this since we're no longer supporting 1.9.4

**Closed as completed by whichonespink44** 2016-10-23 14:17 UTC
Labels: bug, bug: CRITICAL, bug: unconfirmed
