### ISSUE TITLE
very strange beach biome

### ISSUE THREAD

**Issue by Lodugh** [Team-RTG/Realistic-Terrain-Generation#490] opened 2016-02-08 12:46 UTC
Got something to fix for you. Look at this very strange beach biome generation in 0.6..
![2016-02-08_13 23 29](https://cloud.githubusercontent.com/assets/13154183/12885943/393bc136-ce6a-11e5-9ef2-6c5a7669bf0b.png)
I didnt forget to delete the configs. If you need the seed and the position I can give it to you.

**Comment by whichonespink44** [comment] 2016-02-08 13:02
Duplicate of #456 - we're aware of the beach issues and are working to improve them for the nest release.

**Closed by whichonespink44** 2016-02-08 13:02 UTC
Labels: duplicate
