### ISSUE TITLE
Bamboo forests sometimes do not generate properly

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1166] opened 2017-05-08 18:14 UTC
This is rather similar to a previous issue of mine, https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1066

However, it pertains to bamboo forests, on 1.10.2.

https://i.imgur.com/gQorqgA.png

It also seems to sometimes afflict savannas, as well.

https://i.imgur.com/zwoX8aS.png

Other biomes that sometimes get afflicted:

Roofed Forests (presumably, forests are also affected)
Outbacks (strangely vacant, again)
Deserts

Not sure if this is applicable, but I used Nucleus' chunk generation function on the server.

The issue has been replicable with the same seed. 4112307981209916893

Only trees I end up finding in these areas are either from Ars Magica 2, or Harvestcraft.

**Comment by srs-bsns** [comment] 2017-05-08 22:08
There haven't been any issues with biome decoration like this in RTG. If there were we would have known about them a long time ago. This has to be caused by some other mod(s) you are using.

It's unlikely that it's Nucleas because it uses Sponge's chunk generation methods which should be fully compatible with RTG.

Can you reproduce this with just RTG + BoP + GeographiCraft/BiomeTweaker?

I'm going to close this, since it's highly unlikely that it's related to RTG. I'll reopen if you can prove otherwise.

**Closed as completed by srs-bsns** 2017-05-08 22:09 UTC
Labels: bug: unconfirmed, 1.10

**Comment by Sunconure11** [comment] 2017-05-08 23:22
Due to how the issue appears, it is rather hard to replicate at this point, compared to when it afflicted me on 1.7.10.

I wonder, if by any chance if multicraft could somehow cause this though, as I am currently generating the same seed on my own PC, and plan to send it over to a multicraft-based server once its finished.

**Comment by Sunconure11** [comment] 2017-05-23 11:27
Hm, sorry for bringing this issue up again, but by any chance, does multicraft do anything funny that could cause this? Since the server this issue happened on, regardless of version, used multicraft.

**Comment by whichonespink44** [comment] 2017-05-23 15:13
I'm not familiar with Multicraft to be able to comment, but... I suppose it's possible. It seems very strange that it would only be happening to Bamboo Forest though.

**Comment by Sunconure11** [comment] 2017-05-23 15:17
It happened to most biomes, including ones I've had issues with in the past. Only pregenerating the map on my machine solved it.

**Comment by whichonespink44** [comment] 2017-05-23 15:24
Then yeah, that sounds like it could indeed be an issue with Multicraft. Maybe some of their daemons or customization scripts are interfering somehow? No idea to be honest, but if pre-generating with RTG is working fine, then I don't think it could be RTG causing that on a server.

**Comment by Sunconure11** [comment] 2017-05-23 15:25
Hm, so what could be done regarding this, then? The person who owns the machine the server is hosted on hasn't been real... active. I have no clue where she went, really.

**Comment by lightningo7** [comment] 2017-05-23 15:28
I've been using a custom installation of Multicraft for the past year and a half and haven't noticed it affect any kind of terrain generation what so ever. I highly doubt that is the cause however if it is reproducible with the same mods in a Multicraft environment and not outside I suppose it would be the cause.

**Comment by srs-bsns** [comment] 2017-05-24 20:55
@Sunconure11 I'm assuming this is happening on a dedicated server using SpongeForge? (Considering you mentioned Nucleus)

See: #1177

**Comment by Sunconure11** [comment] 2017-05-24 23:04
Yes, but a similar issue also happened on 1.7.10 in the past, using thermos.

What exactly would both be doing that could've caused this?
