### ISSUE TITLE
StackOverflowError and freeze in world generation (Pams's Harvestcraft)

### ISSUE THREAD

**Issue by Dragonfire300** [Team-RTG/Realistic-Terrain-Generation#894] opened 2016-08-12 11:00 UTC
##### Affected Mod Versions:
- Forge version: 12.18.1.2050 (Minecraft 1.10.2)
- RTG version: [1.9.4-2.0.0-alpha.6](https://minecraft.curseforge.com/projects/realistic-terrain-generation/files/2316525)
- Pam's HarvestCraft: [1.9.4-1.10.2b](https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2320919)
##### Issue Description:

With MC and mods listed above MC freezes somtimes when generating new world (both on new world generation and on exploring). It doesn't crash and windows doesn't complain that it isn't responding. It just freezes. This doesn't seem to happen with the default world generator.
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Install MC version and mods listed above using curse client
2. Run MC (keep launcher open)
3. Keep generating new (rtg) worlds until MC freezes and an error appears in the log. OR
4. Generate a new (rtg) world and fly around untilMC freezes and an error appears in the log

I haven't tested other install methods (curse client), OS (win10), PC, mod versions or MC versions...
##### Extra Information:

[latest.log](http://pastebin.com/uwzTSrp0)
[fml-client-latest.log](http://pastebin.com/mr31X721)

PS: For MC 1.11 you'll have to use a lowercase modid as stated in the log files. Shouldn't have anything to do with this issue...

**Comment by ghost** [comment] 2016-08-12 13:11
Yepp, looks like RTG has a problem with Pam's harvestcraft. I have a lot of mods. While I also had the problem - being stuck in the "Loading World" screen - it worked after I removed the mod )Pam's Harvestcraft).

**Comment by srs-bsns** [comment] 2016-08-12 18:49
Dupe of #866

**Closed as completed by srs-bsns** 2016-08-12 18:49 UTC
Labels: duplicate
