### ISSUE TITLE
Server unable to generate world - attempting to reloaded chunk?

### ISSUE THREAD

**Issue by AlexHeaps** [Team-RTG/Realistic-Terrain-Generation#1000] opened 2016-10-15 00:15 UTC
##### Affected Mod Versions:

Biomes O' Plenty - 1.7.10 - 2.1.0.2027
Climate Control - 0.6.Beta59
- Forge version: 1.7.10 - 10.13.4.1614
- RTG version: 1.7.10 - 1.1.1
##### Issue Description:

Server Generation halted by chunk errors.

No Crash, but getting continuous errors along the lines of:

`[13:05:34] [Server thread/WARN] [FML/]: * There is an attempt to load a chunk (-125,-238) in dimension 0 that is already being loaded. This will cause weird chunk breakages.
[13:05:34] [Server thread/WARN] [FML/]: *  at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154)
[13:05:34] [Server thread/WARN] [FML/]: *  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[13:05:34] [Server thread/WARN] [FML/]: *  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[13:05:34] [Server thread/WARN] [FML/]: *  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[13:05:34] [Server thread/WARN] [FML/]: *  at net.minecraft.world.World.func_72964_e(World.java:419)
[13:05:34] [Server thread/WARN] [FML/]: *  at net.minecraft.world.World.func_147439_a(World.java:345)...
[13:05:34] [Server thread/WARN] [FML/]: ****************************************`

This is disabling me from generating a world at all. Will probably have ongoing repercussions when actually in game.
##### Extra Information:

Full Log File (It's pretty long)
https://gist.github.com/AlexHeaps/3c9f55fb7e6f5d1e32141a1f5f2597ac

Also uploaded the file here.
[fml-server-latest.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/530637/fml-server-latest.txt)

**Comment by AlexHeaps** [comment] 2016-10-15 00:16
Just want to add, ISSUE #1000 everybody!

**Comment by whichonespink44** [comment] 2016-10-15 00:37
Not sure if that's a good thing or a bad thing!! ;)

**Comment by AlexHeaps** [comment] 2016-10-15 02:39
Worthy of celebration, nonetheless hahaha.

**Comment by AlexHeaps** [comment] 2016-10-17 18:41
Hi @whichonespink44, Don't mean to bother you, but is there any update on this issue?

**Comment by whichonespink44** [comment] 2016-10-17 21:55
@AlexHeaps Sorry, I forgot to label this one so it slipped through the cracks.

At first glance, it seems to be an interaction bug between RTG & Galacticraft's oil gen, but we'll need to reproduce it our my development environment in order to know for sure.

In order for that happen, we're gonna need you to try to reproduce the crash with as few mods as possible. For exampe, try removing all mods except RTG & Galacticraft (and any dependencies required), and create a new world using the same seed (**-9127011435312095481**)

If it doesn't crash with only those mods, try adding a few more to see it crashes and keep repeating until it does. With any luck, it'll crash with just RTG and Galacticraft, at which point we should be able to reproduce it on our side and hopefully find a fix for it.

**Comment by AlexHeaps** [comment] 2016-10-18 01:13
Thanks @whichonespink44, I've been playing with it this afternoon. Reset the mods folder and started adding them one by one, and reset the configs.
So far, it's working with Galacticraft and Streams. Will report once I've tested all the mods and see what's actually causing it (well, hopefully)

**Comment by AlexHeaps** [comment] 2016-10-18 01:51
Hello again, small update. I've added a lot of core mods that affect world generation. 
Worlds seem to generate fine, but they're taking a hell of a long time due to continuous messages such as:
`Oct 18, 2016 2:47:53 PM climateControl.DimensionManager salvageSpawn
INFO: checking for spawn at 880,464move 12075 ring 55 inRing 195 caches cache: 1, tcache: 16, allocated: 0, tallocated: 0 dimension 0
Oct 18, 2016 2:47:53 PM climateControl.DimensionManager salvageSpawn
INFO: setting spawn at 880,464
Oct 18, 2016 2:47:54 PM climateControl.DimensionManager salvageSpawn
INFO: (-2147483648,-2147483648)(880,464)
Oct 18, 2016 2:47:54 PM climateControl.DimensionManager salvageSpawn
INFO: checking for spawn at 128,912move 13046 ring 57 inRing 278 caches cache: 34, tcache: 19, allocated: 0, tallocated: 0 dimension 0
Oct 18, 2016 2:47:54 PM climateControl.DimensionManager salvageSpawn
INFO: setting spawn at 128,912
Oct 18, 2016 2:47:56 PM climateControl.DimensionManager salvageSpawn
INFO: (-2147483648,-2147483648)(128,912)
Oct 18, 2016 2:47:56 PM climateControl.DimensionManager salvageSpawn
INFO: checking for spawn at -944,608move 14064 ring 59 inRing 376 caches cache: 1, tcache: 16, allocated: 0, tallocated: 0 dimension 0
Oct 18, 2016 2:47:56 PM climateControl.DimensionManager salvageSpawn
INFO: setting spawn at -944,608`

It usually gets stuck at this kind of message for about 3-5 minutes, and then it prepares the spawn area and unloads the dimensions. Any idea what causes this?

**Comment by whichonespink44** [comment] 2016-11-06 22:49
I believe this is Climate Control's spawn rescue system kicking, probably because the seed you were using tried to spawn you in the ocean. I'm closing this, as it seems the world is generating ok, but if you're still getting those salvageSpawn messages, let us know and we'll take a closer look.

**Closed as completed by whichonespink44** 2016-11-06 22:49 UTC
Labels: bug, bug: unconfirmed, 1.7
